/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryCovertZoneStatus struct {
	ZoneStatus *TerritoryZoneStatus `json:"zoneStatus,omitempty"`
	PlayersParticipated *Object `json:"playersParticipated,omitempty"`
	SuccessfulAttempts *Object `json:"successfulAttempts,omitempty"`
}
