/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClientQualityData struct {
	PerformanceLevel *Object `json:"performanceLevel,omitempty"`
	MemoryLevel *Object `json:"memoryLevel,omitempty"`
	GcActivityLevel *Object `json:"gcActivityLevel,omitempty"`
	VfxAllocationLevel *Object `json:"vfxAllocationLevel,omitempty"`
	Flag *Object `json:"flag,omitempty"`
}
