/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LeaderboardStatus struct {
	Rank *Object `json:"rank,omitempty"`
	RankDelta *Object `json:"rankDelta,omitempty"`
	Score *Object `json:"score,omitempty"`
	ScoreDelta *Object `json:"scoreDelta,omitempty"`
	Tier *Object `json:"tier,omitempty"`
}
