/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PowerUpBundle struct {
	Id *Object `json:"id,omitempty"`
	TargetLevel *Object `json:"targetLevel,omitempty"`
	TargetGearTier *Object `json:"targetGearTier,omitempty"`
	AutoSelectTier *Object `json:"autoSelectTier,omitempty"`
}
