/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SeasonLeagueReference struct {
	DefinitionId *Object `json:"definitionId,omitempty"`
	PromoteSystem *Object `json:"promoteSystem,omitempty"`
	PromoteCondition *Object `json:"promoteCondition,omitempty"`
	RewardPreview *Object `json:"rewardPreview,omitempty"`
	PromoteConditionTable *Object `json:"promoteConditionTable,omitempty"`
}
