/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EntryCategoryAllowed struct {
	CategoryId *Object `json:"categoryId,omitempty"`
	MaximumAllowedUnitQuantity *Object `json:"maximumAllowedUnitQuantity,omitempty"`
	MatchType *Object `json:"matchType,omitempty"`
	MinimumRequiredUnitQuantity *Object `json:"minimumRequiredUnitQuantity,omitempty"`
	MinimumUnitRarity *Object `json:"minimumUnitRarity,omitempty"`
	MinimumOwnedUnitQuantity *Object `json:"minimumOwnedUnitQuantity,omitempty"`
	MinimumUnitLevel *Object `json:"minimumUnitLevel,omitempty"`
	MinimumUnitTier *Object `json:"minimumUnitTier,omitempty"`
	MaximumReinforcement *Object `json:"maximumReinforcement,omitempty"`
	CommanderCategoryId *Object `json:"commanderCategoryId,omitempty"`
	MinimumReinforcement *Object `json:"minimumReinforcement,omitempty"`
	MinimumGalacticPower *Object `json:"minimumGalacticPower,omitempty"`
	MandatoryRosterUnit *Object `json:"mandatoryRosterUnit,omitempty"`
	ExcludeCategoryId *Object `json:"excludeCategoryId,omitempty"`
	MinimumRelicTier *Object `json:"minimumRelicTier,omitempty"`
	MinimumModRarity *Object `json:"minimumModRarity,omitempty"`
	MinimumAbilityLevelAvg *Object `json:"minimumAbilityLevelAvg,omitempty"`
	MinimumAbilityLevelAll *Object `json:"minimumAbilityLevelAll,omitempty"`
	LegendLimit *Object `json:"legendLimit,omitempty"`
	UnitGuideMinimumRequiredUnitQuantity *Object `json:"unitGuideMinimumRequiredUnitQuantity,omitempty"`
	BigUnitLimit *Object `json:"bigUnitLimit,omitempty"`
	MandatoryDatacron *MandatoryDatacron `json:"mandatoryDatacron,omitempty"`
	EraExclusive *Object `json:"eraExclusive,omitempty"`
	MinimumEraLevel *Object `json:"minimumEraLevel,omitempty"`
}
