/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarConflictZoneStatus struct {
	ZoneStatus *TerritoryZoneStatus `json:"zoneStatus,omitempty"`
	SquadCapacity *Object `json:"squadCapacity,omitempty"`
	WarSquad *Object `json:"warSquad,omitempty"`
	SquadCount *Object `json:"squadCount,omitempty"`
	DefeatedSquadCount *Object `json:"defeatedSquadCount,omitempty"`
}
