/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SkillDefinitionReference struct {
	SkillId *Object `json:"skillId,omitempty"`
	RequiredTier *Object `json:"requiredTier,omitempty"`
	RequiredRarity *Object `json:"requiredRarity,omitempty"`
	RequiredRelicTier *Object `json:"requiredRelicTier,omitempty"`
}
