/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatMod struct {
	Id *Object `json:"id,omitempty"`
	DefinitionId *Object `json:"definitionId,omitempty"`
	Level *Object `json:"level,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	SellValue *CurrencyItem `json:"sellValue,omitempty"`
	RemoveCost *CurrencyItem `json:"removeCost,omitempty"`
	Locked *Object `json:"locked,omitempty"`
	PrimaryStat *StatModStat `json:"primaryStat,omitempty"`
	SecondaryStat *Object `json:"secondaryStat,omitempty"`
	Xp *Object `json:"xp,omitempty"`
	LevelCost *CurrencyItem `json:"levelCost,omitempty"`
	BonusQuantity *Object `json:"bonusQuantity,omitempty"`
	ConvertedItem *BucketItem `json:"convertedItem,omitempty"`
	RerolledCount *Object `json:"rerolledCount,omitempty"`
}
