/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RecommendedSquad struct {
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	Thumbnail *Object `json:"thumbnail,omitempty"`
	UnitDefId *Object `json:"unitDefId,omitempty"`
	Name *Object `json:"name,omitempty"`
	ShowRequirement *Requirement `json:"showRequirement,omitempty"`
	HideRequirement *Requirement `json:"hideRequirement,omitempty"`
	ActionLink *ActionLink `json:"actionLink,omitempty"`
	Id *Object `json:"id,omitempty"`
}
