/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LinkedStoreItem struct {
	LinkId *Object `json:"linkId,omitempty"`
	StoreItem *Object `json:"storeItem,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	ContextualStoreItem *Object `json:"contextualStoreItem,omitempty"`
}
