/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignNodeEncounter struct {
	EncounterCinematics *Object `json:"encounterCinematics,omitempty"`
	Environment *Object `json:"environment,omitempty"`
	EncounterMessage *Object `json:"encounterMessage,omitempty"`
	AudioKey *Object `json:"audioKey,omitempty"`
	AllowChanceMechanics *Object `json:"allowChanceMechanics,omitempty"`
	FirstTimeEncounterMessage *Object `json:"firstTimeEncounterMessage,omitempty"`
	EncounterIcon *Object `json:"encounterIcon,omitempty"`
	EncounterDescKey *Object `json:"encounterDescKey,omitempty"`
	EncounterIconPosition *Object `json:"encounterIconPosition,omitempty"`
	RaidProgressColor *Object `json:"raidProgressColor,omitempty"`
	MaxDeployedSquadSize *Object `json:"maxDeployedSquadSize,omitempty"`
	EnvironmentCollectionId *Object `json:"environmentCollectionId,omitempty"`
	EncounterId *Object `json:"encounterId,omitempty"`
	EncounterDurationLimit *Object `json:"encounterDurationLimit,omitempty"`
	ScoreToComplete *Object `json:"scoreToComplete,omitempty"`
	DetailDescKey *Object `json:"detailDescKey,omitempty"`
	PointsToComplete *Object `json:"pointsToComplete,omitempty"`
	AudioVictoryKey *Object `json:"audioVictoryKey,omitempty"`
	DisplayableEnemyId *Object `json:"displayableEnemyId,omitempty"`
	DisplayableGrantedAbility *Object `json:"displayableGrantedAbility,omitempty"`
}
