/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BucketItem struct {
	Id *Object `json:"id,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	MinQuantity *Object `json:"minQuantity,omitempty"`
	MaxQuantity *Object `json:"maxQuantity,omitempty"`
	Rarity *Object `json:"rarity,omitempty"`
	StatMod *StatMod `json:"statMod,omitempty"`
	PreviewPriority *Object `json:"previewPriority,omitempty"`
	UnitLevel *Object `json:"unitLevel,omitempty"`
	UnitTier *Object `json:"unitTier,omitempty"`
	PrimaryReward *Object `json:"primaryReward,omitempty"`
}
