/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Ability struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	PrefabName *Object `json:"prefabName,omitempty"`
	TriggerCondition *Object `json:"triggerCondition,omitempty"`
	StackingLineOverride *Object `json:"stackingLineOverride,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	Cooldown *Object `json:"cooldown,omitempty"`
	Icon *Object `json:"icon,omitempty"`
	ApplyTypeTooltipKey *Object `json:"applyTypeTooltipKey,omitempty"`
	DescriptiveTag *Object `json:"descriptiveTag,omitempty"`
	EffectReference *Object `json:"effectReference,omitempty"`
	ConfirmationMessage *MessageDialog `json:"confirmationMessage,omitempty"`
	ButtonLocation *Object `json:"buttonLocation,omitempty"`
	ShortDescKey *Object `json:"shortDescKey,omitempty"`
	AbilityType *Object `json:"abilityType,omitempty"`
	DetailLocation *Object `json:"detailLocation,omitempty"`
	AllyTargetingRuleId *Object `json:"allyTargetingRuleId,omitempty"`
	UseAsReinforcementDesc *Object `json:"useAsReinforcementDesc,omitempty"`
	InteractsWithTag *Object `json:"interactsWithTag,omitempty"`
	SubIcon *Object `json:"subIcon,omitempty"`
	AiParams *AbilityAiParams `json:"aiParams,omitempty"`
	CooldownType *Object `json:"cooldownType,omitempty"`
	AlwaysDisplayInBattleUi *Object `json:"alwaysDisplayInBattleUi,omitempty"`
	HighlightWhenReadyInBattleUi *Object `json:"highlightWhenReadyInBattleUi,omitempty"`
	HideCooldownDescription *Object `json:"hideCooldownDescription,omitempty"`
	BlockingEffectId *Object `json:"blockingEffectId,omitempty"`
	BlockedLocKey *Object `json:"blockedLocKey,omitempty"`
	UltimateChargeRequired *Object `json:"ultimateChargeRequired,omitempty"`
	GrantedPriority *Object `json:"grantedPriority,omitempty"`
	Synergy *AbilitySynergy `json:"synergy,omitempty"`
	VisualTarget *EffectTarget `json:"visualTarget,omitempty"`
}
