/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnitUpgrade struct {
	Id *Object `json:"id,omitempty"`
	Level *Object `json:"level,omitempty"`
	Rarity *Object `json:"rarity,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	SkillTier *Object `json:"skillTier,omitempty"`
	SkillOverride *Object `json:"skillOverride,omitempty"`
	RelicTier *Object `json:"relicTier,omitempty"`
	BasicSkillTier *Object `json:"basicSkillTier,omitempty"`
	LeaderSkillTier *Object `json:"leaderSkillTier,omitempty"`
	UniqueSkillTier *Object `json:"uniqueSkillTier,omitempty"`
	SpecialSkillTier *Object `json:"specialSkillTier,omitempty"`
	ExcludeZetaSkills *Object `json:"excludeZetaSkills,omitempty"`
	ExcludeOmicronSkills *Object `json:"excludeOmicronSkills,omitempty"`
	AbilityDescriptiveTagSkillTier *Object `json:"abilityDescriptiveTagSkillTier,omitempty"`
}
