/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SeasonDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	SeasonLeagueReference *Object `json:"seasonLeagueReference,omitempty"`
	SeasonDivisionReference *Object `json:"seasonDivisionReference,omitempty"`
	SeasonRewardTableId *Object `json:"seasonRewardTableId,omitempty"`
	MinimumBannerSeasonRewardThreshold *Object `json:"minimumBannerSeasonRewardThreshold,omitempty"`
	DivisionSkillBoundary *Object `json:"divisionSkillBoundary,omitempty"`
}
