/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronSetTier struct {
	Id *Object `json:"id,omitempty"`
	UpgradeCostRecipeId *Object `json:"upgradeCostRecipeId,omitempty"`
	DustGrantRecipeId *Object `json:"dustGrantRecipeId,omitempty"`
	RerollCostRecipeId *Object `json:"rerollCostRecipeId,omitempty"`
	ScopeIdentifier *Object `json:"scopeIdentifier,omitempty"`
}
