/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContextualMessage struct {
	Id *Object `json:"id,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	TitleKey *Object `json:"titleKey,omitempty"`
	TextKey *Object `json:"textKey,omitempty"`
	PointAt *PointAtElement `json:"pointAt,omitempty"`
	AppearEvent *Object `json:"appearEvent,omitempty"`
	DismissEvent *Object `json:"dismissEvent,omitempty"`
	HideEvent *Object `json:"hideEvent,omitempty"`
	ActionLink *Object `json:"actionLink,omitempty"`
	NextMessageId *Object `json:"nextMessageId,omitempty"`
	ClientRequirement *Requirement `json:"clientRequirement,omitempty"`
	CharacterDialog *CharacterDialog `json:"characterDialog,omitempty"`
	NextMessageIdDecline *Object `json:"nextMessageIdDecline,omitempty"`
	CanDismissWhileHidden *Object `json:"canDismissWhileHidden,omitempty"`
	FtueSubStep *Object `json:"ftueSubStep,omitempty"`
	CantinaCharacterDialog *CantinaCharacterDialog `json:"cantinaCharacterDialog,omitempty"`
	ActionLinkDef *ActionLink `json:"actionLinkDef,omitempty"`
	StorePromoDialog *StorePromoDialog `json:"storePromoDialog,omitempty"`
	ShowExitButton *Object `json:"showExitButton,omitempty"`
}
