/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CharacterDialog struct {
	CharacterPrefab *Object `json:"characterPrefab,omitempty"`
	Animations *Object `json:"animations,omitempty"`
	AudioKey *Object `json:"audioKey,omitempty"`
	Layout *Object `json:"layout,omitempty"`
	UseHologramEffect *Object `json:"useHologramEffect,omitempty"`
}
