/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SkillDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	IconKey *Object `json:"iconKey,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	AbilityReference *Object `json:"abilityReference,omitempty"`
	SkillType *Object `json:"skillType,omitempty"`
	IsZeta *Object `json:"isZeta,omitempty"`
	OmicronMode *Object `json:"omicronMode,omitempty"`
}
