/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronTemplate struct {
	Id *Object `json:"id,omitempty"`
	SetId *Object `json:"setId,omitempty"`
	InitialTiers *Object `json:"initialTiers,omitempty"`
	ReferenceTemplateId *Object `json:"referenceTemplateId,omitempty"`
	FixedTag *Object `json:"fixedTag,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	MaxRerolls *Object `json:"maxRerolls,omitempty"`
	AllowReroll *Object `json:"allowReroll,omitempty"`
	Focused *Object `json:"focused,omitempty"`
	FocusedIcon *Object `json:"focusedIcon,omitempty"`
	FocusedPrefab *Object `json:"focusedPrefab,omitempty"`
}
