/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameEventInstance struct {
	Id *Object `json:"id,omitempty"`
	StartTime *Object `json:"startTime,omitempty"`
	EndTime *Object `json:"endTime,omitempty"`
	DisplayStartTime *Object `json:"displayStartTime,omitempty"`
	DisplayEndTime *Object `json:"displayEndTime,omitempty"`
	TimeLimited *Object `json:"timeLimited,omitempty"`
	CampaignElementIdentifier *CampaignElementIdentifier `json:"campaignElementIdentifier,omitempty"`
	RewardPreview *Object `json:"rewardPreview,omitempty"`
	RankRewardPreview *Object `json:"rankRewardPreview,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	DefensiveSquadSize *Object `json:"defensiveSquadSize,omitempty"`
	UnitDailyUsageCapKey *Object `json:"unitDailyUsageCapKey,omitempty"`
	RosterRefreshTime *Object `json:"rosterRefreshTime,omitempty"`
	Joined *Object `json:"joined,omitempty"`
	SummaryKey *Object `json:"summaryKey,omitempty"`
	RewardTime *Object `json:"rewardTime,omitempty"`
	DefensiveSquadSaveTimeLimit *Object `json:"defensiveSquadSaveTimeLimit,omitempty"`
	SystemModifier *SystemModifier `json:"systemModifier,omitempty"`
	SupportsPushNotifications *Object `json:"supportsPushNotifications,omitempty"`
	LinkedEventId *Object `json:"linkedEventId,omitempty"`
}
