/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlayerArenaPayload struct {
	AllyCode *Object `json:"allyCode,omitempty"`
	PlayerId *Object `json:"playerId,omitempty"`
	PlayerDetailsOnly *Object `json:"playerDetailsOnly,omitempty"`
}
