/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GuildRaidLaunchConfig struct {
	RaidId *Object `json:"raidId,omitempty"`
	CampaignMissionIdentifier *CampaignElementIdentifier `json:"campaignMissionIdentifier,omitempty"`
	AutoLaunch *Object `json:"autoLaunch,omitempty"`
	AutoLaunchImmediately *Object `json:"autoLaunchImmediately,omitempty"`
	AutoLaunchTime *Object `json:"autoLaunchTime,omitempty"`
	JoinPeriodDuration *Object `json:"joinPeriodDuration,omitempty"`
	AutoSimEnabled *Object `json:"autoSimEnabled,omitempty"`
	Immediate *Object `json:"immediate,omitempty"`
	ScheduledUtcOffsetSeconds *Object `json:"scheduledUtcOffsetSeconds,omitempty"`
}
