/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RelicDefinition struct {
	RelicTierDefinitionId *Object `json:"relicTierDefinitionId,omitempty"`
	UpgradeTableId *Object `json:"upgradeTableId,omitempty"`
	AlignmentColorOverride *Object `json:"alignmentColorOverride,omitempty"`
	Texture *Object `json:"texture,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
}
