/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarPointStructure struct {
	DeployDefensiveSquadReward *TerritoryReward `json:"deployDefensiveSquadReward,omitempty"`
	OffensiveWinReward *TerritoryReward `json:"offensiveWinReward,omitempty"`
	CompleteZoneReward *TerritoryReward `json:"completeZoneReward,omitempty"`
	CompleteZoneRewardPerDefensiveSquad *TerritoryReward `json:"completeZoneRewardPerDefensiveSquad,omitempty"`
	DefendDefeatBonus *Object `json:"defendDefeatBonus,omitempty"`
	EmptySquadSlotBonus *TerritoryReward `json:"emptySquadSlotBonus,omitempty"`
	SurvivingSquadUnitBonus *TerritoryReward `json:"survivingSquadUnitBonus,omitempty"`
	FullHealthUnitBonus *TerritoryReward `json:"fullHealthUnitBonus,omitempty"`
	FullProtectionUnitBonus *TerritoryReward `json:"fullProtectionUnitBonus,omitempty"`
	FirstAttackBonus *TerritoryReward `json:"firstAttackBonus,omitempty"`
	EnemyDefeatedBonus *TerritoryReward `json:"enemyDefeatedBonus,omitempty"`
}
