/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignElementIdentifier struct {
	CampaignId *Object `json:"campaignId,omitempty"`
	CampaignMapId *Object `json:"campaignMapId,omitempty"`
	CampaignNodeId *Object `json:"campaignNodeId,omitempty"`
	CampaignNodeDifficulty *Object `json:"campaignNodeDifficulty,omitempty"`
	CampaignMissionId *Object `json:"campaignMissionId,omitempty"`
}
