/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GuildRaidStatus struct {
	RaidId *Object `json:"raidId,omitempty"`
	ExpireTime *Object `json:"expireTime,omitempty"`
	RaidProgress *Object `json:"raidProgress,omitempty"`
	RaidMemberOld *Object `json:"raidMemberOld,omitempty"`
	OpponentUnitState *Object `json:"opponentUnitState,omitempty"`
	PlayerUnitState *Object `json:"playerUnitState,omitempty"`
	Identifier *CampaignElementIdentifier `json:"identifier,omitempty"`
	InstanceId *Object `json:"instanceId,omitempty"`
	RosterRefreshTime *Object `json:"rosterRefreshTime,omitempty"`
	HasPlayerParticipated *Object `json:"hasPlayerParticipated,omitempty"`
	RaidState *Object `json:"raidState,omitempty"`
	TallyEndTime *Object `json:"tallyEndTime,omitempty"`
	EligibleForRewards *Object `json:"eligibleForRewards,omitempty"`
	ActivateTimeMs *Object `json:"activateTimeMs,omitempty"`
	ForbidLateEntry *Object `json:"forbidLateEntry,omitempty"`
	JoinPeriodEndTimeMs *Object `json:"joinPeriodEndTimeMs,omitempty"`
	RaidMember *Object `json:"raidMember,omitempty"`
	SimEnabled *Object `json:"simEnabled,omitempty"`
	EncounterId *Object `json:"encounterId,omitempty"`
	LastEncounterIdPlayerParticipated *Object `json:"lastEncounterIdPlayerParticipated,omitempty"`
	CurrentEncounterPointsScored *Object `json:"currentEncounterPointsScored,omitempty"`
	GuildRewardScore *Object `json:"guildRewardScore,omitempty"`
	IneligibleMemberId *Object `json:"ineligibleMemberId,omitempty"`
	ClaimedImmediateRewards *Object `json:"claimedImmediateRewards,omitempty"`
	CachedRewards *CachedRaidRewards `json:"cachedRewards,omitempty"`
	ExhaustedDatacronId *Object `json:"exhaustedDatacronId,omitempty"`
}
