/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnitBattleStat struct {
	ActionCountMin *Object `json:"actionCountMin,omitempty"`
	ActionCountMax *Object `json:"actionCountMax,omitempty"`
	BattleStat *StatDef `json:"battleStat,omitempty"`
	Level *Object `json:"level,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	Equipment *Object `json:"equipment,omitempty"`
	Skill *Object `json:"skill,omitempty"`
	StatMod *Object `json:"statMod,omitempty"`
	UnitDefId *Object `json:"unitDefId,omitempty"`
	UnitId *Object `json:"unitId,omitempty"`
	UnitRelicTier *Object `json:"unitRelicTier,omitempty"`
	PurchasedAbilityId *Object `json:"purchasedAbilityId,omitempty"`
	OverrideAllStatsMultiplier *Object `json:"overrideAllStatsMultiplier,omitempty"`
	OverrideStatMultiplier *Object `json:"overrideStatMultiplier,omitempty"`
	SkipStatsOverwrite *Object `json:"skipStatsOverwrite,omitempty"`
	EnableLeaderAbility *Object `json:"enableLeaderAbility,omitempty"`
	ThreatLevelOverride *Object `json:"threatLevelOverride,omitempty"`
	OverrideAllStatsTable *Object `json:"overrideAllStatsTable,omitempty"`
	EraLevel *Object `json:"eraLevel,omitempty"`
}
