/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Challenge struct {
	Id *Object `json:"id,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	ViewRequirement *Requirement `json:"viewRequirement,omitempty"`
	Reward *Object `json:"reward,omitempty"`
	PlatformAchievementId *Object `json:"platformAchievementId,omitempty"`
	ActionLinkDef *ActionLink `json:"actionLinkDef,omitempty"`
	ClaimType *Object `json:"claimType,omitempty"`
	RewardType *Object `json:"rewardType,omitempty"`
	RewardRatio *Object `json:"rewardRatio,omitempty"`
	Task *Object `json:"task,omitempty"`
	MessageGroup *ContextualMessageGroup `json:"messageGroup,omitempty"`
	StyleId *Object `json:"styleId,omitempty"`
	Priority *Object `json:"priority,omitempty"`
	NextChallengeId *Object `json:"nextChallengeId,omitempty"`
	RewardDialogKey *Object `json:"rewardDialogKey,omitempty"`
	RewardRedirectToHome *Object `json:"rewardRedirectToHome,omitempty"`
	RewardDescKey *Object `json:"rewardDescKey,omitempty"`
	StarterGuildGraduation *Object `json:"starterGuildGraduation,omitempty"`
	RewardPoints *Object `json:"rewardPoints,omitempty"`
	DetailsKey *Object `json:"detailsKey,omitempty"`
	HiddenInMainQuests *Object `json:"hiddenInMainQuests,omitempty"`
	ClaimRequirement *Requirement `json:"claimRequirement,omitempty"`
	RewardPopupEnabled *Object `json:"rewardPopupEnabled,omitempty"`
	ClaimDisabled *Object `json:"claimDisabled,omitempty"`
	ClaimDisabledMessageKey *Object `json:"claimDisabledMessageKey,omitempty"`
	DescParameterKey *Object `json:"descParameterKey,omitempty"`
}
