/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryTournamentDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	PrefabName *Object `json:"prefabName,omitempty"`
	IconPrefab *Object `json:"iconPrefab,omitempty"`
	DetailImage *Object `json:"detailImage,omitempty"`
	TerritoryCategory *Object `json:"territoryCategory,omitempty"`
	MinimapPrefab *Object `json:"minimapPrefab,omitempty"`
	RoundCount *Object `json:"roundCount,omitempty"`
	RoundTallyDuration *Object `json:"roundTallyDuration,omitempty"`
	MatchmakingDuration *Object `json:"matchmakingDuration,omitempty"`
	DynamicDescription *Object `json:"dynamicDescription,omitempty"`
	CompleteRankRewardPreview *Object `json:"completeRankRewardPreview,omitempty"`
	GrantedAbilities *Object `json:"grantedAbilities,omitempty"`
	LocalNotifications *Object `json:"localNotifications,omitempty"`
	RestrictSetupDuringAttackPhase *Object `json:"restrictSetupDuringAttackPhase,omitempty"`
	ConflictZoneDefinition *Object `json:"conflictZoneDefinition,omitempty"`
	DuelZoneDefinition *Object `json:"duelZoneDefinition,omitempty"`
	NoJoinDuration *Object `json:"noJoinDuration,omitempty"`
	DefensiveCharacterDeployWarningThreshold *Object `json:"defensiveCharacterDeployWarningThreshold,omitempty"`
	DefensiveShipDeployWarningThreshold *Object `json:"defensiveShipDeployWarningThreshold,omitempty"`
	MatchCount *Object `json:"matchCount,omitempty"`
	RoundRewardPreview *Object `json:"roundRewardPreview,omitempty"`
	SeasonPointsPerBannerPercent *Object `json:"seasonPointsPerBannerPercent,omitempty"`
	RoundSeasonRewardTableId *Object `json:"roundSeasonRewardTableId,omitempty"`
	MinimumBannerRoundRewardThreshold *Object `json:"minimumBannerRoundRewardThreshold,omitempty"`
	MinimumBannerEventRewardThreshold *Object `json:"minimumBannerEventRewardThreshold,omitempty"`
	SavedSquadConfigId *Object `json:"savedSquadConfigId,omitempty"`
}
