/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GuildMember struct {
	PlayerId *Object `json:"playerId,omitempty"`
	PlayerName *Object `json:"playerName,omitempty"`
	PlayerLevel *Object `json:"playerLevel,omitempty"`
	MemberLevel *Object `json:"memberLevel,omitempty"`
	GuildXp *Object `json:"guildXp,omitempty"`
	LastActivityTime *Object `json:"lastActivityTime,omitempty"`
	SquadPower *Object `json:"squadPower,omitempty"`
	MemberContribution *Object `json:"memberContribution,omitempty"`
	GuildJoinTime *Object `json:"guildJoinTime,omitempty"`
	GalacticPower *Object `json:"galacticPower,omitempty"`
	PlayerTitle *Object `json:"playerTitle,omitempty"`
	PlayerPortrait *Object `json:"playerPortrait,omitempty"`
	SeasonStatus *Object `json:"seasonStatus,omitempty"`
	LifetimeSeasonScore *Object `json:"lifetimeSeasonScore,omitempty"`
	LeagueId *Object `json:"leagueId,omitempty"`
	ShipGalacticPower *Object `json:"shipGalacticPower,omitempty"`
	CharacterGalacticPower *Object `json:"characterGalacticPower,omitempty"`
	NucleusId *Object `json:"nucleusId,omitempty"`
}
