/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RaidModifier struct {
	DescKey *Object `json:"descKey,omitempty"`
	GrantedAbility *Object `json:"grantedAbility,omitempty"`
	ScoreMultiplierUnscaled *Object `json:"scoreMultiplierUnscaled,omitempty"`
	RequiredUnitTier *Object `json:"requiredUnitTier,omitempty"`
	RequiredRelicTier *Object `json:"requiredRelicTier,omitempty"`
	AbilityOverride *Object `json:"abilityOverride,omitempty"`
	OverrideRelicTier *Object `json:"overrideRelicTier,omitempty"`
}
