/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GuildRaidConfig struct {
	Id *Object `json:"id,omitempty"`
	RaidType *Object `json:"raidType,omitempty"`
	RosterRefreshType *Object `json:"rosterRefreshType,omitempty"`
	RosterRefresh *GuildRaidRosterRefresh `json:"rosterRefresh,omitempty"`
	RaidDuration *Object `json:"raidDuration,omitempty"`
}
