/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SocialStatus struct {
	ChatIcons *Object `json:"chatIcons,omitempty"`
	ChatTitles *Object `json:"chatTitles,omitempty"`
	GuildLogo *Object `json:"guildLogo,omitempty"`
	GuildColor *Object `json:"guildColor,omitempty"`
	ChatPortraits *Object `json:"chatPortraits,omitempty"`
}
