/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConsumableDefinition struct {
	Id *Object `json:"id,omitempty"`
	TierId *Object `json:"tierId,omitempty"`
	IconKey *Object `json:"iconKey,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	TotalBattleUse *Object `json:"totalBattleUse,omitempty"`
	GrantedAbility *Object `json:"grantedAbility,omitempty"`
	StaminaRecovery *Object `json:"staminaRecovery,omitempty"`
	TargetedStat *Object `json:"targetedStat,omitempty"`
	ConsumableTypeId *Object `json:"consumableTypeId,omitempty"`
	EffectIconKey *Object `json:"effectIconKey,omitempty"`
	ActiveTimeInSeconds *Object `json:"activeTimeInSeconds,omitempty"`
	StaminaRegenTimeReduction *Object `json:"staminaRegenTimeReduction,omitempty"`
	EnergyRegenTimeReduction *Object `json:"energyRegenTimeReduction,omitempty"`
}
