/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlayerTitleDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	Obtainable *Object `json:"obtainable,omitempty"`
	Hidden *Object `json:"hidden,omitempty"`
	ShortDescKey *Object `json:"shortDescKey,omitempty"`
}
