/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MetadataPayloadClientSpecs struct {
	Platform *Object `json:"platform,omitempty"`
	BundleId *Object `json:"bundleId,omitempty"`
	ExternalVersion *Object `json:"externalVersion,omitempty"`
	InternalVersion *Object `json:"internalVersion,omitempty"`
	Region *Object `json:"region,omitempty"`
}
