/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Effect struct {
	Id *Object `json:"id,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	Param *Object `json:"param,omitempty"`
	Chance *Object `json:"chance,omitempty"`
	Target *Object `json:"target,omitempty"`
	DescriptiveTag *Object `json:"descriptiveTag,omitempty"`
	EffectedTag *Object `json:"effectedTag,omitempty"`
	TriggerCondition *Object `json:"triggerCondition,omitempty"`
	EffectDefinition *Object `json:"effectDefinition,omitempty"`
	ContextIndex *Object `json:"contextIndex,omitempty"`
	ExpirationCondition *Object `json:"expirationCondition,omitempty"`
	ApplyType *Object `json:"applyType,omitempty"`
	DamageType *Object `json:"damageType,omitempty"`
	PersistentIcon *Object `json:"persistentIcon,omitempty"`
	TriggeredVfx *Object `json:"triggeredVfx,omitempty"`
	TriggeredLocKey *Object `json:"triggeredLocKey,omitempty"`
	MaxBonusMoves *Object `json:"maxBonusMoves,omitempty"`
	EffectReference *Object `json:"effectReference,omitempty"`
	MultiplierAmountDecimal *Object `json:"multiplierAmountDecimal,omitempty"`
	ContextMultiplierDecimal *Object `json:"contextMultiplierDecimal,omitempty"`
	AdditiveAmountDecimal *Object `json:"additiveAmountDecimal,omitempty"`
	ResultVarianceDecimal *Object `json:"resultVarianceDecimal,omitempty"`
	PersistentLocKey *Object `json:"persistentLocKey,omitempty"`
	StackingLineOverride *Object `json:"stackingLineOverride,omitempty"`
	PersistentIconOverlay *Object `json:"persistentIconOverlay,omitempty"`
	PersistentIconPriority *Object `json:"persistentIconPriority,omitempty"`
	IconColor *Object `json:"iconColor,omitempty"`
	PersistentIconGroupable *Object `json:"persistentIconGroupable,omitempty"`
	PersistentVfxReference *PersistentVfxReference `json:"persistentVfxReference,omitempty"`
	BlackboardName *Object `json:"blackboardName,omitempty"`
	SummonId *Object `json:"summonId,omitempty"`
	SummonEffect *Object `json:"summonEffect,omitempty"`
	SummonLevel *Object `json:"summonLevel,omitempty"`
	SummonTier *Object `json:"summonTier,omitempty"`
	SummonRarity *Object `json:"summonRarity,omitempty"`
	SummonSquadIncrease *Object `json:"summonSquadIncrease,omitempty"`
	IgnoreDamageAnimation *Object `json:"ignoreDamageAnimation,omitempty"`
	InfiniteCycleEffect *Object `json:"infiniteCycleEffect,omitempty"`
	BlackboardCompareName *Object `json:"blackboardCompareName,omitempty"`
	SummonMarkerIndex *Object `json:"summonMarkerIndex,omitempty"`
	SummonEnableInitialVfx *Object `json:"summonEnableInitialVfx,omitempty"`
	SummonCount *Object `json:"summonCount,omitempty"`
	TriggerOnApplication *Object `json:"triggerOnApplication,omitempty"`
	ExpireOnApplication *Object `json:"expireOnApplication,omitempty"`
	ReplaceTableId *Object `json:"replaceTableId,omitempty"`
	ApplyEffectEnabled *Object `json:"applyEffectEnabled,omitempty"`
	ApplyEffectLabel *Object `json:"applyEffectLabel,omitempty"`
	SummonEraLevel *Object `json:"summonEraLevel,omitempty"`
}
