/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryTournamentLeagueDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	Icon *Object `json:"icon,omitempty"`
	Rank *Object `json:"rank,omitempty"`
	Sprite *Object `json:"sprite,omitempty"`
	PortraitFrame *Object `json:"portraitFrame,omitempty"`
	BlankIcon *Object `json:"blankIcon,omitempty"`
}
