/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Recipe struct {
	Id *Object `json:"id,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	Result *BucketItem `json:"result,omitempty"`
	Ingredients *Object `json:"ingredients,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	ViewRequirement *Requirement `json:"viewRequirement,omitempty"`
	UnlockLevel *Object `json:"unlockLevel,omitempty"`
	CraftRequirement *Requirement `json:"craftRequirement,omitempty"`
	RequiredEraLevel *Object `json:"requiredEraLevel,omitempty"`
}
