/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EffectReference struct {
	Id *Object `json:"id,omitempty"`
	ContextIndex *Object `json:"contextIndex,omitempty"`
	MaxBonusMove *Object `json:"maxBonusMove,omitempty"`
}
