/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatModStat struct {
	Stat *Stat `json:"stat,omitempty"`
	Roll *Object `json:"roll,omitempty"`
	StatRolls *Object `json:"statRolls,omitempty"`
	StatRollerBoundsMin *Object `json:"statRollerBoundsMin,omitempty"`
	StatRollerBoundsMax *Object `json:"statRollerBoundsMax,omitempty"`
	UnscaledRollValue *Object `json:"unscaledRollValue,omitempty"`
}
