/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryZoneDefinition struct {
	ZoneId *Object `json:"zoneId,omitempty"`
	PrefabName *Object `json:"prefabName,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	LinkedConflictId *Object `json:"linkedConflictId,omitempty"`
	MaxAttemptsAllowed *Object `json:"maxAttemptsAllowed,omitempty"`
	UnlockRequirement *Requirement `json:"unlockRequirement,omitempty"`
	MaxUnitCountPerPlayer *Object `json:"maxUnitCountPerPlayer,omitempty"`
	GrantedAbilities *Object `json:"grantedAbilities,omitempty"`
	DetailViewIconOverrideName *Object `json:"detailViewIconOverrideName,omitempty"`
	MapIconOverrideName *Object `json:"mapIconOverrideName,omitempty"`
}
