/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SkillTierDefinition struct {
	RecipeId *Object `json:"recipeId,omitempty"`
	RequiredUnitLevel *Object `json:"requiredUnitLevel,omitempty"`
	RequiredUnitRarity *Object `json:"requiredUnitRarity,omitempty"`
	RequiredUnitTier *Object `json:"requiredUnitTier,omitempty"`
	PowerOverrideTag *Object `json:"powerOverrideTag,omitempty"`
	RequiredUnitRelicTier *Object `json:"requiredUnitRelicTier,omitempty"`
	IsZetaTier *Object `json:"isZetaTier,omitempty"`
	IsOmicronTier *Object `json:"isOmicronTier,omitempty"`
}
