/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryZoneStatus struct {
	ZoneId *Object `json:"zoneId,omitempty"`
	ZoneState *Object `json:"zoneState,omitempty"`
	Score *Object `json:"score,omitempty"`
	ChannelId *Object `json:"channelId,omitempty"`
	CommandMessage *Object `json:"commandMessage,omitempty"`
	CommandState *Object `json:"commandState,omitempty"`
}
