/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EnergyRewardDefinition struct {
	EnergyType *Object `json:"energyType,omitempty"`
	Instance *Object `json:"instance,omitempty"`
	ClaimableTitleKey *Object `json:"claimableTitleKey,omitempty"`
	ClaimableDescKey *Object `json:"claimableDescKey,omitempty"`
	UpcomingTitleKey *Object `json:"upcomingTitleKey,omitempty"`
	UpcomingDescKey *Object `json:"upcomingDescKey,omitempty"`
	ShowRequirement *Requirement `json:"showRequirement,omitempty"`
}
