/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ArtifactDefinition struct {
	Id *Object `json:"id,omitempty"`
	PowerLevel *Object `json:"powerLevel,omitempty"`
	GrantedAbility *Object `json:"grantedAbility,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	Texture *Object `json:"texture,omitempty"`
	TargetedStat *Object `json:"targetedStat,omitempty"`
	TierId *Object `json:"tierId,omitempty"`
}
