/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryLocalNote struct {
	MessageKey *Object `json:"messageKey,omitempty"`
	TitleKey *Object `json:"titleKey,omitempty"`
	OptedIn *Object `json:"optedIn,omitempty"`
	Phase *Object `json:"phase,omitempty"`
	PhaseTimeOffsetSeconds *Object `json:"phaseTimeOffsetSeconds,omitempty"`
	FinalMatchOnly *Object `json:"finalMatchOnly,omitempty"`
	PerSubPhaseRoundEnd *Object `json:"perSubPhaseRoundEnd,omitempty"`
}
