/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GalacticBundle struct {
	Id *Object `json:"id,omitempty"`
	TargetPlayerLevel *Object `json:"targetPlayerLevel,omitempty"`
	UnitUpgrade *Object `json:"unitUpgrade,omitempty"`
	Tabs *Object `json:"tabs,omitempty"`
	InventoryItem *Object `json:"inventoryItem,omitempty"`
	Info *Object `json:"info,omitempty"`
	PrimaryGalacticBundle *Object `json:"primaryGalacticBundle,omitempty"`
}
