/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EraLevelDefinition struct {
	Level *Object `json:"level,omitempty"`
	UpgradeRecipeId *Object `json:"upgradeRecipeId,omitempty"`
	RequiredRarity *Object `json:"requiredRarity,omitempty"`
	MajorMilestone *Object `json:"majorMilestone,omitempty"`
	CurrentUnitLevel *Object `json:"currentUnitLevel,omitempty"`
	CurrentGearTier *Object `json:"currentGearTier,omitempty"`
	CurrentGearPieces *Object `json:"currentGearPieces,omitempty"`
	CurrentRelicTier *Object `json:"currentRelicTier,omitempty"`
	CurrentAbilityLevel *Object `json:"currentAbilityLevel,omitempty"`
}
