/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2Xx1 struct {
	Units *Object `json:"units,omitempty"`
	BattleEnvironments *Object `json:"battleEnvironments,omitempty"`
	XpTable *Object `json:"xpTable,omitempty"`
	Material *Object `json:"material,omitempty"`
	Recipe *Object `json:"recipe,omitempty"`
	StatProgression *Object `json:"statProgression,omitempty"`
	Category *Object `json:"category,omitempty"`
	HelpEntry *Object `json:"helpEntry,omitempty"`
	Challenge *Object `json:"challenge,omitempty"`
	Skill *Object `json:"skill,omitempty"`
	EventSampling *Object `json:"eventSampling,omitempty"`
	Equipment *Object `json:"equipment,omitempty"`
	WarDefinition *Object `json:"warDefinition,omitempty"`
	TargetingSet *Object `json:"targetingSet,omitempty"`
	Ability *Object `json:"ability,omitempty"`
	Effect *Object `json:"effect,omitempty"`
	Requirement *Object `json:"requirement,omitempty"`
	PowerUpBundle *Object `json:"powerUpBundle,omitempty"`
	GuildBanner *GuildBannerDef `json:"guildBanner,omitempty"`
	RaidConfig *Object `json:"raidConfig,omitempty"`
	GuildRaid *Object `json:"guildRaid,omitempty"`
	StatModSet *Object `json:"statModSet,omitempty"`
	StatMod *Object `json:"statMod,omitempty"`
	GuildExchangeItem *Object `json:"guildExchangeItem,omitempty"`
	Table *Object `json:"table,omitempty"`
	UnlockAnnouncementDefinition *Object `json:"unlockAnnouncementDefinition,omitempty"`
	BattleTargetingRule *Object `json:"battleTargetingRule,omitempty"`
	TerritoryBattleDefinition *Object `json:"territoryBattleDefinition,omitempty"`
	TerritoryWarDefinition *Object `json:"territoryWarDefinition,omitempty"`
	EnvironmentCollection *Object `json:"environmentCollection,omitempty"`
	ChallengeStyle *Object `json:"challengeStyle,omitempty"`
	SocialStatus *SocialStatus `json:"socialStatus,omitempty"`
	StarterGuild *Object `json:"starterGuild,omitempty"`
	PlayerTitle *Object `json:"playerTitle,omitempty"`
	ModRecommendation *Object `json:"modRecommendation,omitempty"`
	PersistentVfx *Object `json:"persistentVfx,omitempty"`
	TerritoryTournamentDefinition *Object `json:"territoryTournamentDefinition,omitempty"`
	EventBonus *Object `json:"eventBonus,omitempty"`
	SeasonDefinition *Object `json:"seasonDefinition,omitempty"`
	PlayerPortrait *Object `json:"playerPortrait,omitempty"`
	TimeZoneChangeConfig *TimeZoneChangeConfig `json:"timeZoneChangeConfig,omitempty"`
	EffectIconPriority *Object `json:"effectIconPriority,omitempty"`
	MysteryBox *Object `json:"mysteryBox,omitempty"`
	MysteryStatMod *Object `json:"mysteryStatMod,omitempty"`
	Cooldown *Object `json:"cooldown,omitempty"`
	DailyActionCap *Object `json:"dailyActionCap,omitempty"`
	EnergyReward *Object `json:"energyReward,omitempty"`
	SeasonLeagueDefinition *Object `json:"seasonLeagueDefinition,omitempty"`
	SeasonDivisionDefinition *Object `json:"seasonDivisionDefinition,omitempty"`
	SeasonRewardTable *Object `json:"seasonRewardTable,omitempty"`
	RelicTierDefinition *Object `json:"relicTierDefinition,omitempty"`
	ScavengerConversionSet *Object `json:"scavengerConversionSet,omitempty"`
	UnitGuideDefinition *Object `json:"unitGuideDefinition,omitempty"`
	GalacticBundle *Object `json:"galacticBundle,omitempty"`
	LinkedStoreItem *Object `json:"linkedStoreItem,omitempty"`
	TerritoryTournamentLeagueDefinition *Object `json:"territoryTournamentLeagueDefinition,omitempty"`
	TerritoryTournamentDivisionDefinition *Object `json:"territoryTournamentDivisionDefinition,omitempty"`
	SavedSquadConfig *Object `json:"savedSquadConfig,omitempty"`
	GuildRaidGlobalConfig *GuildRaidGlobalConfig `json:"guildRaidGlobalConfig,omitempty"`
	LightspeedToken *Object `json:"lightspeedToken,omitempty"`
	Campaign *Object `json:"campaign,omitempty"`
	ConquestDefinition *Object `json:"conquestDefinition,omitempty"`
	ConquestMission *Object `json:"conquestMission,omitempty"`
	ArtifactDefinition *Object `json:"artifactDefinition,omitempty"`
	AbilityDecisionTree *Object `json:"abilityDecisionTree,omitempty"`
	ConsumableDefinition *Object `json:"consumableDefinition,omitempty"`
	ConsumableType *Object `json:"consumableType,omitempty"`
	ArtifactTierDefinition *Object `json:"artifactTierDefinition,omitempty"`
	ConsumableTierDefinition *Object `json:"consumableTierDefinition,omitempty"`
	RecommendedSquad *Object `json:"recommendedSquad,omitempty"`
	UnitGuideLayout *Object `json:"unitGuideLayout,omitempty"`
	DailyLoginRewardDefinition *Object `json:"dailyLoginRewardDefinition,omitempty"`
	CalendarCategoryDefinition *Object `json:"calendarCategoryDefinition,omitempty"`
	TerritoryTournamentDailyRewardTable *TerritoryTournamentDailyRewardTable `json:"territoryTournamentDailyRewardTable,omitempty"`
	DatacronSet *Object `json:"datacronSet,omitempty"`
	DatacronTemplate *Object `json:"datacronTemplate,omitempty"`
	DatacronAffixTemplateSet *Object `json:"datacronAffixTemplateSet,omitempty"`
	DatacronHelpEntry *Object `json:"datacronHelpEntry,omitempty"`
	DisplayableEnemy *Object `json:"displayableEnemy,omitempty"`
	EpisodeDefinition *Object `json:"episodeDefinition,omitempty"`
	LinkingReward *BucketItem `json:"linkingReward,omitempty"`
	EraDefinition *Object `json:"eraDefinition,omitempty"`
}
