/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarGuildStatus struct {
	Profile *TerritoryGuildProfile `json:"profile,omitempty"`
	ConflictStatus *Object `json:"conflictStatus,omitempty"`
	ReconStatus *Object `json:"reconStatus,omitempty"`
}
