/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SeasonStatus struct {
	SeasonId *Object `json:"seasonId,omitempty"`
	EventInstanceId *Object `json:"eventInstanceId,omitempty"`
	League *Object `json:"league,omitempty"`
	Wins *Object `json:"wins,omitempty"`
	Losses *Object `json:"losses,omitempty"`
	SeasonPoints *Object `json:"seasonPoints,omitempty"`
	Division *Object `json:"division,omitempty"`
	JoinTime *Object `json:"joinTime,omitempty"`
	EndTime *Object `json:"endTime,omitempty"`
	Remove *Object `json:"remove,omitempty"`
	Rank *Object `json:"rank,omitempty"`
}
