/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AbilityAiParams struct {
	PreferredAllyTargetingRuleId *Object `json:"preferredAllyTargetingRuleId,omitempty"`
	PreferredEnemyTargetingRuleId *Object `json:"preferredEnemyTargetingRuleId,omitempty"`
	RequireEnemyPreferredTargets *Object `json:"requireEnemyPreferredTargets,omitempty"`
	RequireAllyTargets *Object `json:"requireAllyTargets,omitempty"`
	PreferredAllyTargetingRuleIdList *Object `json:"preferredAllyTargetingRuleIdList,omitempty"`
	PreferredEnemyTargetingRuleIdList *Object `json:"preferredEnemyTargetingRuleIdList,omitempty"`
}
