/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConquestDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	ConquestDifficulty *Object `json:"conquestDifficulty,omitempty"`
	StaminaStatAllowlist *Object `json:"staminaStatAllowlist,omitempty"`
	ConsumableDetail *Object `json:"consumableDetail,omitempty"`
	Visibility *Object `json:"visibility,omitempty"`
	MiscEntry *Object `json:"miscEntry,omitempty"`
}
