/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StarterGuildDef struct {
	GuildType *Object `json:"guildType,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	AllowedRaidId *Object `json:"allowedRaidId,omitempty"`
	MessageKey *Object `json:"messageKey,omitempty"`
	AllowedRaidCampaignId *Object `json:"allowedRaidCampaignId,omitempty"`
	BannerLogoId *Object `json:"bannerLogoId,omitempty"`
	BannerColorId *Object `json:"bannerColorId,omitempty"`
	ExternalMessageKey *Object `json:"externalMessageKey,omitempty"`
	SubNameKey *Object `json:"subNameKey,omitempty"`
}
