/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MissionGrantedAbility struct {
	AbilityId *Object `json:"abilityId,omitempty"`
	TargetRuleId *Object `json:"targetRuleId,omitempty"`
	UnlockRequirement *Requirement `json:"unlockRequirement,omitempty"`
	RankLabelOverrideKey *Object `json:"rankLabelOverrideKey,omitempty"`
	UseOverlayIcon *Object `json:"useOverlayIcon,omitempty"`
	OverlaySpriteName *Object `json:"overlaySpriteName,omitempty"`
	ZonesToApplyTo *Object `json:"zonesToApplyTo,omitempty"`
	ShowInPlatoonView *Object `json:"showInPlatoonView,omitempty"`
	ModifierData *AbilityModifierData `json:"modifierData,omitempty"`
	ConditionDescKey *Object `json:"conditionDescKey,omitempty"`
}
