/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnitDefPreview struct {
	Id *Object `json:"id,omitempty"`
	ThumbnailName *Object `json:"thumbnailName,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	BasicAttackRef *AbilityReference `json:"basicAttackRef,omitempty"`
	LimitBreakRef *Object `json:"limitBreakRef,omitempty"`
	UniqueAbilityRef *Object `json:"uniqueAbilityRef,omitempty"`
}
