/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EpisodeDefinition struct {
	Id *Object `json:"id,omitempty"`
	StartTime *Object `json:"startTime,omitempty"`
	EndTime *Object `json:"endTime,omitempty"`
	RegularImmediateRankRewardPreview *Object `json:"regularImmediateRankRewardPreview,omitempty"`
	PremiumImmediateRankRewardPreview *Object `json:"premiumImmediateRankRewardPreview,omitempty"`
	RepeatableMilestone *RepeatableMilestone `json:"repeatableMilestone,omitempty"`
	Title *Object `json:"title,omitempty"`
	EpisodeQuestBlock *Object `json:"episodeQuestBlock,omitempty"`
	CharacterQuestLine *Object `json:"characterQuestLine,omitempty"`
	ObjectivesViewBackground *Object `json:"objectivesViewBackground,omitempty"`
	PurchasePassPopupBackground *Object `json:"purchasePassPopupBackground,omitempty"`
	EpisodePassIcon *Object `json:"episodePassIcon,omitempty"`
	PurchasePassPopupCenterImageBack *Object `json:"purchasePassPopupCenterImageBack,omitempty"`
	PurchasePassPopupCenterImageFront *Object `json:"purchasePassPopupCenterImageFront,omitempty"`
	EpisodePassIconFree *Object `json:"episodePassIconFree,omitempty"`
	EpisodePassIconPremium *Object `json:"episodePassIconPremium,omitempty"`
	IntroQuestBlock *Object `json:"introQuestBlock,omitempty"`
}
