/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MandatoryDatacron struct {
	MinLevel *Object `json:"minLevel,omitempty"`
	SetId *Object `json:"setId,omitempty"`
	TemplateId *Object `json:"templateId,omitempty"`
}
