/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LocalizationPayload struct {
	// The localization bundle ID from the /metadata response can be appended with the locale desired to decrease the response size, example: ':ENG_US'
	Id *Object `json:"id"`
}
