/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronSetMaterial struct {
	MaterialId *Object `json:"materialId,omitempty"`
	QuantityPerDustGrant *Object `json:"quantityPerDustGrant,omitempty"`
	DustGrantRecipeId *Object `json:"dustGrantRecipeId,omitempty"`
}
