/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatModDefinition struct {
	Id *Object `json:"id,omitempty"`
	Slot *Object `json:"slot,omitempty"`
	SetId *Object `json:"setId,omitempty"`
	Rarity *Object `json:"rarity,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	MissionLookup *Object `json:"missionLookup,omitempty"`
	RaidLookup *Object `json:"raidLookup,omitempty"`
	ActionLinkLookup *Object `json:"actionLinkLookup,omitempty"`
	LevelTableId *Object `json:"levelTableId,omitempty"`
	PromotionId *Object `json:"promotionId,omitempty"`
	PromotionRecipeId *Object `json:"promotionRecipeId,omitempty"`
	TierUpRecipeTableId *Object `json:"tierUpRecipeTableId,omitempty"`
	OverclockRecipeTableId *Object `json:"overclockRecipeTableId,omitempty"`
	RerollCapTableId *Object `json:"rerollCapTableId,omitempty"`
	RaidImmediateLookup *Object `json:"raidImmediateLookup,omitempty"`
}
