/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChallengeStyle struct {
	Id *Object `json:"id,omitempty"`
	ButtonIcon *Object `json:"buttonIcon,omitempty"`
	CharacterIcon *Object `json:"characterIcon,omitempty"`
	CharacterNameKey *Object `json:"characterNameKey,omitempty"`
	CharacterRewardIcon *Object `json:"characterRewardIcon,omitempty"`
	CompleteKey *Object `json:"completeKey,omitempty"`
	AudioKey *Object `json:"audioKey,omitempty"`
	QuestTitleKey *Object `json:"questTitleKey,omitempty"`
}
