/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModifierItem struct {
	Type_ *Object `json:"type,omitempty"`
	MaterialType *Object `json:"materialType,omitempty"`
	Id *Object `json:"id,omitempty"`
	Category *Object `json:"category,omitempty"`
}
