/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DataPayload struct {
	Version *Object `json:"version"`
	// Whether to include pve units in the collections or not.
	IncludePveUnits *Object `json:"includePveUnits,omitempty"`
	DevicePlatform *Object `json:"devicePlatform,omitempty"`
	// Mutually exclusive with the items parameter. Uses the game data segment enums.
	RequestSegment *Object `json:"requestSegment,omitempty"`
	// Mutually exclusive with the requestSegment parameter. Uses a binary bit mask converted to integer string where each collection to include in the response is represented by its digit being set to 1 to include, 0 to not include.
	Items *Object `json:"items,omitempty"`
}
