/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SquadCell struct {
	UnitId *Object `json:"unitId,omitempty"`
	UnitDefId *Object `json:"unitDefId,omitempty"`
	CellIndex *Object `json:"cellIndex,omitempty"`
	UnitBattleStat *UnitBattleStat `json:"unitBattleStat,omitempty"`
	MessageReticle *Object `json:"messageReticle,omitempty"`
	ProgressItem *Object `json:"progressItem,omitempty"`
	SquadUnitType *Object `json:"squadUnitType,omitempty"`
	CrewBattleStat *Object `json:"crewBattleStat,omitempty"`
	UnitState *BattleUnitState `json:"unitState,omitempty"`
	Selectable *Object `json:"selectable,omitempty"`
	OverkillItem *Object `json:"overkillItem,omitempty"`
	InheritFromDefinitionId *Object `json:"inheritFromDefinitionId,omitempty"`
	ForcedUnitEraLevel *Object `json:"forcedUnitEraLevel,omitempty"`
}
