/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryGuildProfile struct {
	Id *Object `json:"id,omitempty"`
	Name *Object `json:"name,omitempty"`
	LogoBackground *Object `json:"logoBackground,omitempty"`
	BannerColorId *Object `json:"bannerColorId,omitempty"`
	BannerLogoId *Object `json:"bannerLogoId,omitempty"`
	GuildGalacticPower *Object `json:"guildGalacticPower,omitempty"`
}
