/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CrewMember struct {
	UnitId *Object `json:"unitId,omitempty"`
	Slot *Object `json:"slot,omitempty"`
	SkillReference *Object `json:"skillReference,omitempty"`
	SkilllessCrewAbilityId *Object `json:"skilllessCrewAbilityId,omitempty"`
}
