/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnlockAnnouncementDefinition struct {
	Feature *Object `json:"feature,omitempty"`
	StartOffset *Object `json:"startOffset,omitempty"`
	Interval *Object `json:"interval,omitempty"`
	MessageKey *Object `json:"messageKey,omitempty"`
}
