/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EadpParameters struct {
	EadpBaseUrl *Object `json:"eadpBaseUrl,omitempty"`
	EaMobileClientId *Object `json:"eaMobileClientId,omitempty"`
	EadpBaseUrlClient *Object `json:"eadpBaseUrlClient,omitempty"`
	EadpAllowedCryptKey *Object `json:"eadpAllowedCryptKey,omitempty"`
	EadpClientId *Object `json:"eadpClientId,omitempty"`
	EadpWindowsEncryptSeed *Object `json:"eadpWindowsEncryptSeed,omitempty"`
	EadpWindowsContentId *Object `json:"eadpWindowsContentId,omitempty"`
	EadpWindowsMultiplayerId *Object `json:"eadpWindowsMultiplayerId,omitempty"`
	EadpWindowsTitle *Object `json:"eadpWindowsTitle,omitempty"`
	EadpWindowsCommerceGroupName *Object `json:"eadpWindowsCommerceGroupName,omitempty"`
	EadpClientSecret *Object `json:"eadpClientSecret,omitempty"`
	EadpEnv *Object `json:"eadpEnv,omitempty"`
	EadpWindowsAchievementCode *Object `json:"eadpWindowsAchievementCode,omitempty"`
}
