/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignNodeMission struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	EnemyPreview *Object `json:"enemyPreview,omitempty"`
	RewardPreview *Object `json:"rewardPreview,omitempty"`
	CampaignNodeEncounter *Object `json:"campaignNodeEncounter,omitempty"`
	AudioKey *Object `json:"audioKey,omitempty"`
	Progress *Object `json:"progress,omitempty"`
	EntryCostRequirement *Object `json:"entryCostRequirement,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	ShortNameKey *Object `json:"shortNameKey,omitempty"`
	GroupNameKey *Object `json:"groupNameKey,omitempty"`
	GroupImage *Object `json:"groupImage,omitempty"`
	UnlockRequirementLocalizationKey *Object `json:"unlockRequirementLocalizationKey,omitempty"`
	CooldownKey *Object `json:"cooldownKey,omitempty"`
	DailyBattleCapKey *Object `json:"dailyBattleCapKey,omitempty"`
	FirstCompleteRewardPreview *Object `json:"firstCompleteRewardPreview,omitempty"`
	EnemyUnitPreview *Object `json:"enemyUnitPreview,omitempty"`
	Prefab *Object `json:"prefab,omitempty"`
	Position *Position `json:"position,omitempty"`
	PlayerAbilityRef *Object `json:"playerAbilityRef,omitempty"`
	ActivateCost *Object `json:"activateCost,omitempty"`
	RankRewardPreview *Object `json:"rankRewardPreview,omitempty"`
	DetailImage *Object `json:"detailImage,omitempty"`
	DetailDescKey *Object `json:"detailDescKey,omitempty"`
	RaidConfigId *Object `json:"raidConfigId,omitempty"`
	DynamicDescription *Object `json:"dynamicDescription,omitempty"`
	NodeDisplayItem *Object `json:"nodeDisplayItem,omitempty"`
	GrindEnabled *Object `json:"grindEnabled,omitempty"`
	HasForcedAlly *Object `json:"hasForcedAlly,omitempty"`
	BattleSupportAllowed *Object `json:"battleSupportAllowed,omitempty"`
	AutoBattleEnabled *Object `json:"autoBattleEnabled,omitempty"`
	RetreatEnabled *Object `json:"retreatEnabled,omitempty"`
	ForcedPlayerSquad *ForcedPlayerSquad `json:"forcedPlayerSquad,omitempty"`
	GrantedAbilities *Object `json:"grantedAbilities,omitempty"`
	CooldownConditionalOverrideKey *Object `json:"cooldownConditionalOverrideKey,omitempty"`
	HolonodePlanetPrefabName *Object `json:"holonodePlanetPrefabName,omitempty"`
	BattleSpeedAdjustable *Object `json:"battleSpeedAdjustable,omitempty"`
	RequirementOverrideKey *Object `json:"requirementOverrideKey,omitempty"`
	SimmableOverrideEnabled *Object `json:"simmableOverrideEnabled,omitempty"`
	ConditionalRewardsPreview *Object `json:"conditionalRewardsPreview,omitempty"`
	ConditionalEntryCostOverride *ConditionalBucket `json:"conditionalEntryCostOverride,omitempty"`
	RecommendationKey *Object `json:"recommendationKey,omitempty"`
	InstanceFirstCompleteRewardPreview *Object `json:"instanceFirstCompleteRewardPreview,omitempty"`
	OverviewLocKey *Object `json:"overviewLocKey,omitempty"`
	RecommendedGp *Object `json:"recommendedGp,omitempty"`
	BattleDurationLimit *Object `json:"battleDurationLimit,omitempty"`
	RecommendedUnitGp *Object `json:"recommendedUnitGp,omitempty"`
	VolatileAccess *Object `json:"volatileAccess,omitempty"`
	UnlockRequirementId *Object `json:"unlockRequirementId,omitempty"`
	VisibilityRequirementId *Object `json:"visibilityRequirementId,omitempty"`
	RaidPointsStructure *RaidPointsStructure `json:"raidPointsStructure,omitempty"`
	Featured *Object `json:"featured,omitempty"`
	ImmediateRegularRankRewardPreview *Object `json:"immediateRegularRankRewardPreview,omitempty"`
	MaxPointsPerAttempt *Object `json:"maxPointsPerAttempt,omitempty"`
	UnitReplacement *Object `json:"unitReplacement,omitempty"`
	PveDatacronAllowed *Object `json:"pveDatacronAllowed,omitempty"`
	ColiseumPointSource *Object `json:"coliseumPointSource,omitempty"`
	RecommendedEraLevel *Object `json:"recommendedEraLevel,omitempty"`
}
