/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Unit struct {
	Id *Object `json:"id,omitempty"`
	DefinitionId *Object `json:"definitionId,omitempty"`
	CurrentRarity *Object `json:"currentRarity,omitempty"`
	CurrentLevel *Object `json:"currentLevel,omitempty"`
	CurrentXp *Object `json:"currentXp,omitempty"`
	PromotionRecipeReference *Object `json:"promotionRecipeReference,omitempty"`
	Skill *Object `json:"skill,omitempty"`
	UnitStat *StatDef `json:"unitStat,omitempty"`
	Equipment *Object `json:"equipment,omitempty"`
	CurrentTier *Object `json:"currentTier,omitempty"`
	EquippedStatModOld *Object `json:"equippedStatModOld,omitempty"`
	EquippedStatMod *Object `json:"equippedStatMod,omitempty"`
	Relic *Relic `json:"relic,omitempty"`
	PurchasedAbilityId *Object `json:"purchasedAbilityId,omitempty"`
}
