/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryBattleDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	PrefabName *Object `json:"prefabName,omitempty"`
	RoundDuration *Object `json:"roundDuration,omitempty"`
	RoundCount *Object `json:"roundCount,omitempty"`
	ConflictZoneDefinition *Object `json:"conflictZoneDefinition,omitempty"`
	StrikeZoneDefinition *Object `json:"strikeZoneDefinition,omitempty"`
	ReconZoneDefinition *Object `json:"reconZoneDefinition,omitempty"`
	IconPrefab *Object `json:"iconPrefab,omitempty"`
	RankRewardPreview *Object `json:"rankRewardPreview,omitempty"`
	DetailImage *Object `json:"detailImage,omitempty"`
	DynamicDescription *Object `json:"dynamicDescription,omitempty"`
	CovertZoneDefinition *Object `json:"covertZoneDefinition,omitempty"`
	StatCategory *Object `json:"statCategory,omitempty"`
	TerritoryCategory *Object `json:"territoryCategory,omitempty"`
	RoundTallyDuration *Object `json:"roundTallyDuration,omitempty"`
	GrantedAbilities *Object `json:"grantedAbilities,omitempty"`
	LocalNotifications *Object `json:"localNotifications,omitempty"`
	MinMemberLevelForCommandingGuild *Object `json:"minMemberLevelForCommandingGuild,omitempty"`
	CommandNotificationCooldownDuration *Object `json:"commandNotificationCooldownDuration,omitempty"`
	MinimapPrefab *Object `json:"minimapPrefab,omitempty"`
	SearchImage *Object `json:"searchImage,omitempty"`
	InfoImage *Object `json:"infoImage,omitempty"`
	ForceAlignment *Object `json:"forceAlignment,omitempty"`
	EnvironmentNameKey *Object `json:"environmentNameKey,omitempty"`
	EnvironmentPrefab *Object `json:"environmentPrefab,omitempty"`
	TerritoryBattleVersion3 *Object `json:"territoryBattleVersion_3,omitempty"`
	BonusZoneDefinition *Object `json:"bonusZoneDefinition,omitempty"`
}
