/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameEvent struct {
	Id *Object `json:"id,omitempty"`
	Priority *Object `json:"priority,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	SummaryKey *Object `json:"summaryKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	Image *Object `json:"image,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	Instance *Object `json:"instance,omitempty"`
	Status *Object `json:"status,omitempty"`
	CampaignElementIdentifier *CampaignElementIdentifier `json:"campaignElementIdentifier,omitempty"`
	SquadType *Object `json:"squadType,omitempty"`
	PreviewKey *Object `json:"previewKey,omitempty"`
	ReviewKey *Object `json:"reviewKey,omitempty"`
	UiLocation *Object `json:"uiLocation,omitempty"`
	Icon *Object `json:"icon,omitempty"`
	DefensiveSquadUsageCostEnabled *Object `json:"defensiveSquadUsageCostEnabled,omitempty"`
	EncounterMessage *Object `json:"encounterMessage,omitempty"`
	Environment *Object `json:"environment,omitempty"`
	DescKeyUnitCriteriaMet *Object `json:"descKeyUnitCriteriaMet,omitempty"`
	DefensiveSquadType *Object `json:"defensiveSquadType,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	ImageEffect *Object `json:"imageEffect,omitempty"`
	UnlockRequirementLocalizationKey *Object `json:"unlockRequirementLocalizationKey,omitempty"`
	TerritoryMapId *Object `json:"territoryMapId,omitempty"`
	PushNotificationTitleKey *Object `json:"pushNotificationTitleKey,omitempty"`
	PushNotificationDescKey *Object `json:"pushNotificationDescKey,omitempty"`
	SeasonDefId *Object `json:"seasonDefId,omitempty"`
	UnlockRequirementId *Object `json:"unlockRequirementId,omitempty"`
	Feat *Object `json:"feat,omitempty"`
	LinkedStoreItemId *Object `json:"linkedStoreItemId,omitempty"`
	FactionImage *Object `json:"factionImage,omitempty"`
	DetailsType *Object `json:"detailsType,omitempty"`
	ConquestId *Object `json:"conquestId,omitempty"`
	RankRewardPreview *Object `json:"rankRewardPreview,omitempty"`
	IconJoin *Object `json:"iconJoin,omitempty"`
	IconSetDefense *Object `json:"iconSetDefense,omitempty"`
	IconAttack *Object `json:"iconAttack,omitempty"`
	MarqueeUnitBaseId *Object `json:"marqueeUnitBaseId,omitempty"`
	MarqueeUnitTexture *Object `json:"marqueeUnitTexture,omitempty"`
	HideCompleted *Object `json:"hideCompleted,omitempty"`
}
