/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WarDef struct {
	Id *Object `json:"id,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	Difficulty *Object `json:"difficulty,omitempty"`
	DailyResetCapKey *Object `json:"dailyResetCapKey,omitempty"`
	Node *Object `json:"node,omitempty"`
	Bracket *Object `json:"bracket,omitempty"`
}
