/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarConflictZoneDefinition struct {
	ZoneDefinition *TerritoryZoneDefinition `json:"zoneDefinition,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	ConflictImage *Object `json:"conflictImage,omitempty"`
	ConflictRequirement *Object `json:"conflictRequirement,omitempty"`
	ConflictDetail *Object `json:"conflictDetail,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	DefenseEntryCategoryAllowed *EntryCategoryAllowed `json:"defenseEntryCategoryAllowed,omitempty"`
	DeployDefensiveSquadReward *TerritoryReward `json:"deployDefensiveSquadReward,omitempty"`
	OffensiveWinReward *TerritoryReward `json:"offensiveWinReward,omitempty"`
	CompleteZoneReward *TerritoryReward `json:"completeZoneReward,omitempty"`
	CompleteZoneRewardPerDefensiveSquad *TerritoryReward `json:"completeZoneRewardPerDefensiveSquad,omitempty"`
	BattleEnvironments *Object `json:"battleEnvironments,omitempty"`
	PointStructure *TerritoryWarPointStructure `json:"pointStructure,omitempty"`
}
