/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignNodeDifficultyGroup struct {
	CampaignNodeDifficulty *Object `json:"campaignNodeDifficulty,omitempty"`
	CampaignNode *Object `json:"campaignNode,omitempty"`
	Progress *Object `json:"progress,omitempty"`
	UnlockRequirementLocalizationKey *Object `json:"unlockRequirementLocalizationKey,omitempty"`
	DailyBattleCapKey *Object `json:"dailyBattleCapKey,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	GrindEnabled *Object `json:"grindEnabled,omitempty"`
}
