/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EquipmentDef struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	IconKey *Object `json:"iconKey,omitempty"`
	RequiredLevel *Object `json:"requiredLevel,omitempty"`
	EquipmentStat *StatDef `json:"equipmentStat,omitempty"`
	RecipeId *Object `json:"recipeId,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	SellValue *CurrencyItem `json:"sellValue,omitempty"`
	LookupMission *Object `json:"lookupMission,omitempty"`
	Mark *Object `json:"mark,omitempty"`
	ObtainableTime *Object `json:"obtainableTime,omitempty"`
	RaidLookup *Object `json:"raidLookup,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	ActionLinkLookup *Object `json:"actionLinkLookup,omitempty"`
	RequiredRarity *Object `json:"requiredRarity,omitempty"`
	FindFlowDisabled *Object `json:"findFlowDisabled,omitempty"`
	RaidImmediateLookup *Object `json:"raidImmediateLookup,omitempty"`
}
