/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnitGuideDefinition struct {
	UnitBaseId *Object `json:"unitBaseId,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	ActivityId *Object `json:"activityId,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	RecommendationRequirementId *Object `json:"recommendationRequirementId,omitempty"`
	OverrideTexture *Object `json:"overrideTexture,omitempty"`
	TitleKey *Object `json:"titleKey,omitempty"`
	SubtitleKey *Object `json:"subtitleKey,omitempty"`
	AdditionalActivationRequirementId *Object `json:"additionalActivationRequirementId,omitempty"`
	DisplayEnabled *Object `json:"displayEnabled,omitempty"`
	ActionLinkImage *Object `json:"actionLinkImage,omitempty"`
	ActionLink *Object `json:"actionLink,omitempty"`
	InPreview *Object `json:"inPreview,omitempty"`
	HiddenUnitCount *Object `json:"hiddenUnitCount,omitempty"`
	PreviewArtImage *Object `json:"previewArtImage,omitempty"`
	UpcomingEventKey *Object `json:"upcomingEventKey,omitempty"`
	Featured *Object `json:"featured,omitempty"`
	CampaignElementIdentifier *CampaignElementIdentifier `json:"campaignElementIdentifier,omitempty"`
	CharacterRecommendedEntryCategory *EntryCategoryAllowed `json:"characterRecommendedEntryCategory,omitempty"`
	ShipRecommendedEntryCategory *EntryCategoryAllowed `json:"shipRecommendedEntryCategory,omitempty"`
	GalacticLegend *Object `json:"galacticLegend,omitempty"`
	BannerImage *Object `json:"bannerImage,omitempty"`
	BannerImageSubtextKey *Object `json:"bannerImageSubtextKey,omitempty"`
	UnitStagePrefab *Object `json:"unitStagePrefab,omitempty"`
}
