/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatModSetDefinition struct {
	Id *Object `json:"id,omitempty"`
	Name *Object `json:"name,omitempty"`
	Icon *Object `json:"icon,omitempty"`
	CompleteBonus *StatModSetBonus `json:"completeBonus,omitempty"`
	MaxLevelBonus *StatModSetBonus `json:"maxLevelBonus,omitempty"`
	SetCount *Object `json:"setCount,omitempty"`
	OverclockBonus *StatModSetBonus `json:"overclockBonus,omitempty"`
}
