/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DailyLoginRewardDefinition struct {
	Id *Object `json:"id,omitempty"`
	Title *Object `json:"title,omitempty"`
	Message *Object `json:"message,omitempty"`
	DefaultBucketItem *BucketItem `json:"defaultBucketItem,omitempty"`
	Reward *Object `json:"reward,omitempty"`
	Monthly *Object `json:"monthly,omitempty"`
	MissedConsequence *Object `json:"missedConsequence,omitempty"`
	CompletionBehavior *Object `json:"completionBehavior,omitempty"`
	Icon *Object `json:"icon,omitempty"`
	Category *Object `json:"category,omitempty"`
	DelayFirstReward *Object `json:"delayFirstReward,omitempty"`
	CatchUp *Object `json:"catchUp,omitempty"`
	Expiry *CalendarExpiry `json:"expiry,omitempty"`
	VisualOverride *CalendarVisuals `json:"visualOverride,omitempty"`
	CatchupCost *BucketItem `json:"catchupCost,omitempty"`
}
