/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TimeZoneChangeConfig struct {
	AllowedChangesPerPeriod *Object `json:"allowedChangesPerPeriod,omitempty"`
	AllowedChangesLocKey *Object `json:"allowedChangesLocKey,omitempty"`
	AllowedChangesResetLocKey *Object `json:"allowedChangesResetLocKey,omitempty"`
	MaxTimeZoneChangeHoursExclusive *Object `json:"maxTimeZoneChangeHoursExclusive,omitempty"`
	TimeZoneDefinition *Object `json:"timeZoneDefinition,omitempty"`
	TimeZoneChangeCooldownId *Object `json:"timeZoneChangeCooldownId,omitempty"`
}
