/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronAffixTemplate struct {
	AbilityId *Object `json:"abilityId,omitempty"`
	TargetRule *Object `json:"targetRule,omitempty"`
	StatType *Object `json:"statType,omitempty"`
	StatValueMin *Object `json:"statValueMin,omitempty"`
	StatValueMax *Object `json:"statValueMax,omitempty"`
	MinTier *Object `json:"minTier,omitempty"`
	MaxTier *Object `json:"maxTier,omitempty"`
	Tag *Object `json:"tag,omitempty"`
	ScopeIcon *Object `json:"scopeIcon,omitempty"`
}
