/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RaidAbilityOverride struct {
	AbilityId *Object `json:"abilityId,omitempty"`
	TargetRuleId *Object `json:"targetRuleId,omitempty"`
	LocKey *Object `json:"locKey,omitempty"`
	Icon *Object `json:"icon,omitempty"`
}
