/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MysteryStatModDefinition struct {
	Id *Object `json:"id,omitempty"`
	SlotOld *Object `json:"slotOld,omitempty"`
	SetId *Object `json:"setId,omitempty"`
	MinRarity *Object `json:"minRarity,omitempty"`
	MaxRarity *Object `json:"maxRarity,omitempty"`
	MinTier *Object `json:"minTier,omitempty"`
	MaxTier *Object `json:"maxTier,omitempty"`
	Slot *Object `json:"slot,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
}
