/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignNode struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	CampaignNodeMission *Object `json:"campaignNodeMission,omitempty"`
	HomePrefab *Object `json:"homePrefab,omitempty"`
	ForceAlignment *Object `json:"forceAlignment,omitempty"`
	DominantClass *Object `json:"dominantClass,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	IsCannon *Object `json:"isCannon,omitempty"`
	Progress *Object `json:"progress,omitempty"`
	UnlockRequirementLocalizationKey *Object `json:"unlockRequirementLocalizationKey,omitempty"`
	DailyBattleCapKey *Object `json:"dailyBattleCapKey,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	CooldownKey *Object `json:"cooldownKey,omitempty"`
	GrindEnabled *Object `json:"grindEnabled,omitempty"`
	CooldownConditionalOverrideKey *Object `json:"cooldownConditionalOverrideKey,omitempty"`
	FirstTimeFinishCost *Object `json:"firstTimeFinishCost,omitempty"`
}
