/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequirementItem struct {
	Type_ *Object `json:"type,omitempty"`
	Id *Object `json:"id,omitempty"`
	Value *Object `json:"value,omitempty"`
	LocKey *Object `json:"locKey,omitempty"`
	Negate *Object `json:"negate,omitempty"`
	RosterUnitType *Object `json:"rosterUnitType,omitempty"`
}
