/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronTemplateTier struct {
	Id *Object `json:"id,omitempty"`
	AffixTemplateSetId *Object `json:"affixTemplateSetId,omitempty"`
	InitialAffixTemplateSetIds *Object `json:"initialAffixTemplateSetIds,omitempty"`
	RequiredUnitTier *Object `json:"requiredUnitTier,omitempty"`
	RequiredRelicTier *Object `json:"requiredRelicTier,omitempty"`
	OverrideUpgradeCostRecipeId *Object `json:"overrideUpgradeCostRecipeId,omitempty"`
	OverrideScopeIdentifier *Object `json:"overrideScopeIdentifier,omitempty"`
}
