/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PointAtElement struct {
	ElementId *Object `json:"elementId,omitempty"`
	OffsetX *Object `json:"offsetX,omitempty"`
	OffsetY *Object `json:"offsetY,omitempty"`
	Rotation *Object `json:"rotation,omitempty"`
	TextOffsetX *Object `json:"textOffsetX,omitempty"`
	TextOffsetY *Object `json:"textOffsetY,omitempty"`
	TextOffsetAnchor *Object `json:"textOffsetAnchor,omitempty"`
	Update *Object `json:"update,omitempty"`
	Clamp *Object `json:"clamp,omitempty"`
	RotationBehavior *Object `json:"rotationBehavior,omitempty"`
	DelaySeconds *Object `json:"delaySeconds,omitempty"`
	ShowArrow *Object `json:"showArrow,omitempty"`
	ShowHighlight *Object `json:"showHighlight,omitempty"`
	ImageSource *Object `json:"imageSource,omitempty"`
	ImageWidth *Object `json:"imageWidth,omitempty"`
	ImageHeight *Object `json:"imageHeight,omitempty"`
	ImageOffsetX *Object `json:"imageOffsetX,omitempty"`
	ImageOffsetY *Object `json:"imageOffsetY,omitempty"`
	PointerType *Object `json:"pointerType,omitempty"`
	TapDismiss *Object `json:"tapDismiss,omitempty"`
	ScrimVisible *Object `json:"scrimVisible,omitempty"`
	ScrimBlocking *Object `json:"scrimBlocking,omitempty"`
	ShowText *Object `json:"showText,omitempty"`
	ShowBartender *Object `json:"showBartender,omitempty"`
	BartenderTexture *Object `json:"bartenderTexture,omitempty"`
}
