/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GuildProfile struct {
	Id *Object `json:"id,omitempty"`
	Name *Object `json:"name,omitempty"`
	ExternalMessageKey *Object `json:"externalMessageKey,omitempty"`
	MessageCriteriaKey *Object `json:"messageCriteriaKey,omitempty"`
	LogoBackground *Object `json:"logoBackground,omitempty"`
	EnrollmentStatus *Object `json:"enrollmentStatus,omitempty"`
	Trophy *Object `json:"trophy,omitempty"`
	MemberCount *Object `json:"memberCount,omitempty"`
	MemberMax *Object `json:"memberMax,omitempty"`
	Level *Object `json:"level,omitempty"`
	Rank *Object `json:"rank,omitempty"`
	LevelRequirement *Object `json:"levelRequirement,omitempty"`
	RaidWin *Object `json:"raidWin,omitempty"`
	LeaderboardScore *Object `json:"leaderboardScore,omitempty"`
	BannerColorId *Object `json:"bannerColorId,omitempty"`
	BannerLogoId *Object `json:"bannerLogoId,omitempty"`
	GuildGalacticPower *Object `json:"guildGalacticPower,omitempty"`
	ChatChannelId *Object `json:"chatChannelId,omitempty"`
	GuildType *Object `json:"guildType,omitempty"`
	RaidLaunchConfig *Object `json:"raidLaunchConfig,omitempty"`
	GuildEventTracker *Object `json:"guildEventTracker,omitempty"`
	GuildGalacticPowerForRequirement *Object `json:"guildGalacticPowerForRequirement,omitempty"`
	SingleLaunchConfig *GuildRaidLaunchConfig `json:"singleLaunchConfig,omitempty"`
	AutoLaunchConfig *GuildRaidLaunchConfig `json:"autoLaunchConfig,omitempty"`
}
