/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronSet struct {
	Id *Object `json:"id,omitempty"`
	DisplayName *Object `json:"displayName,omitempty"`
	ExpirationTimeMs *Object `json:"expirationTimeMs,omitempty"`
	Icon *Object `json:"icon,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	DetailPrefab *Object `json:"detailPrefab,omitempty"`
	SetMaterial *Object `json:"setMaterial,omitempty"`
	FocusedTier *Object `json:"focusedTier,omitempty"`
}
