/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContentSegmentFile struct {
	Id *Object `json:"id,omitempty"`
	Filters *Object `json:"filters,omitempty"`
	Path *Object `json:"path,omitempty"`
	GroupId *Object `json:"groupId,omitempty"`
	Size *Object `json:"size,omitempty"`
}
