/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignMap struct {
	Id *Object `json:"id,omitempty"`
	CampaignNodeDifficultyGroup *Object `json:"campaignNodeDifficultyGroup,omitempty"`
	Progress *Object `json:"progress,omitempty"`
	EntryOwnershipRequirement *Object `json:"entryOwnershipRequirement,omitempty"`
	UnlockRequirementLocalizationKey *Object `json:"unlockRequirementLocalizationKey,omitempty"`
	IsPlayerSquadSupplied *Object `json:"isPlayerSquadSupplied,omitempty"`
	DailyBattleCapKey *Object `json:"dailyBattleCapKey,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	GrindEnabled *Object `json:"grindEnabled,omitempty"`
	GameModeKey *Object `json:"gameModeKey,omitempty"`
}
