/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2Xx9 struct {
	Name *Object `json:"name,omitempty"`
	Level *Object `json:"level,omitempty"`
	AllyCode *Object `json:"allyCode,omitempty"`
	PlayerId *Object `json:"playerId,omitempty"`
	PvpProfile *Object `json:"pvpProfile,omitempty"`
	LocalTimeZoneOffsetMinutes *Object `json:"localTimeZoneOffsetMinutes,omitempty"`
	LifetimeSeasonScore *Object `json:"lifetimeSeasonScore,omitempty"`
	PlayerRating *PlayerRating `json:"playerRating,omitempty"`
	NucleusId *Object `json:"nucleusId,omitempty"`
}
