/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventSampling struct {
	EventId *Object `json:"eventId,omitempty"`
	SpenderValue *Object `json:"spenderValue,omitempty"`
	NonSpenderValue *Object `json:"nonSpenderValue,omitempty"`
}
