/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronBattleStat struct {
	Id *Object `json:"id,omitempty"`
	SetId *Object `json:"setId,omitempty"`
	TemplateId *Object `json:"templateId,omitempty"`
	Tag *Object `json:"tag,omitempty"`
	Affix *Object `json:"affix,omitempty"`
	HighestTierApplied *Object `json:"highestTierApplied,omitempty"`
}
