/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ColiseumBossSchedule struct {
	BossIndex *Object `json:"bossIndex,omitempty"`
	StartTime *Object `json:"startTime,omitempty"`
	ReviewTime *Object `json:"reviewTime,omitempty"`
	EndTime *Object `json:"endTime,omitempty"`
	EraDayIndex *Object `json:"eraDayIndex,omitempty"`
}
