/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MysteryBoxDefinition struct {
	Id *Object `json:"id,omitempty"`
	Texture *Object `json:"texture,omitempty"`
	TitleKey *Object `json:"titleKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	DetailsTitleKey *Object `json:"detailsTitleKey,omitempty"`
	DetailsDescKey *Object `json:"detailsDescKey,omitempty"`
	IconTextKey *Object `json:"iconTextKey,omitempty"`
	PreviewItem *Object `json:"previewItem,omitempty"`
	ShowPrimaryRewards *Object `json:"showPrimaryRewards,omitempty"`
}
