/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ColiseumBossDefinition struct {
	Identifier *CampaignElementIdentifier `json:"identifier,omitempty"`
	UnitPrefab *Object `json:"unitPrefab,omitempty"`
	EnvironmentPrefab *Object `json:"environmentPrefab,omitempty"`
	BossRewardTable *Object `json:"bossRewardTable,omitempty"`
	CantinaPrefab *Object `json:"cantinaPrefab,omitempty"`
	BossHighlightText *Object `json:"bossHighlightText,omitempty"`
	ShortIntroCinematic *Object `json:"shortIntroCinematic,omitempty"`
	MediumIntroCinematic *Object `json:"mediumIntroCinematic,omitempty"`
	LongIntroCinematic *Object `json:"longIntroCinematic,omitempty"`
}
