/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GalacticBundleMainElement struct {
	Page *Object `json:"page,omitempty"`
	ElementType *Object `json:"elementType,omitempty"`
	Image *Object `json:"image,omitempty"`
	Title *Object `json:"title,omitempty"`
	Description *Object `json:"description,omitempty"`
	InventoryType *Object `json:"inventoryType,omitempty"`
}
