/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Squad struct {
	Cell *Object `json:"cell,omitempty"`
	TargetingTactic *Object `json:"targetingTactic,omitempty"`
	SquadType *Object `json:"squadType,omitempty"`
	TargetingSetId *Object `json:"targetingSetId,omitempty"`
	ExpireTime *Object `json:"expireTime,omitempty"`
	LastSaveTime *Object `json:"lastSaveTime,omitempty"`
	SupportInheritFromDefinitionId *Object `json:"supportInheritFromDefinitionId,omitempty"`
	Datacron *DatacronBattleStat `json:"datacron,omitempty"`
}
