/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnitDef struct {
	Id *Object `json:"id,omitempty"`
	UnitPrefab *Object `json:"unitPrefab,omitempty"`
	ThumbnailName *Object `json:"thumbnailName,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	Rarity *Object `json:"rarity,omitempty"`
	MaxRarity *Object `json:"maxRarity,omitempty"`
	ForceAlignment *Object `json:"forceAlignment,omitempty"`
	XpTableId *Object `json:"xpTableId,omitempty"`
	ActionCountMin *Object `json:"actionCountMin,omitempty"`
	ActionCountMax *Object `json:"actionCountMax,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	ThreatLevel *Object `json:"threatLevel,omitempty"`
	Obtainable *Object `json:"obtainable,omitempty"`
	BaseId *Object `json:"baseId,omitempty"`
	PromotionRecipeReference *Object `json:"promotionRecipeReference,omitempty"`
	StatProgressionId *Object `json:"statProgressionId,omitempty"`
	CategoryId *Object `json:"categoryId,omitempty"`
	TrainingXpWorthBaseValueOverride *Object `json:"trainingXpWorthBaseValueOverride,omitempty"`
	MaxLevelOverride *Object `json:"maxLevelOverride,omitempty"`
	TrainingCostMultiplierOverride *Object `json:"trainingCostMultiplierOverride,omitempty"`
	CreationRecipeReference *Object `json:"creationRecipeReference,omitempty"`
	SkillReference *Object `json:"skillReference,omitempty"`
	BasePower *Object `json:"basePower,omitempty"`
	BaseStat *StatDef `json:"baseStat,omitempty"`
	PrimaryStat *Object `json:"primaryStat,omitempty"`
	UnitTier *Object `json:"unitTier,omitempty"`
	BasicAttack *Ability `json:"basicAttack,omitempty"`
	LeaderAbility *Ability `json:"leaderAbility,omitempty"`
	LimitBreak *Object `json:"limitBreak,omitempty"`
	UniqueAbility *Object `json:"uniqueAbility,omitempty"`
	BasicAttackRef *AbilityReference `json:"basicAttackRef,omitempty"`
	LeaderAbilityRef *AbilityReference `json:"leaderAbilityRef,omitempty"`
	LimitBreakRef *Object `json:"limitBreakRef,omitempty"`
	UniqueAbilityRef *Object `json:"uniqueAbilityRef,omitempty"`
	PrimaryUnitStat *Object `json:"primaryUnitStat,omitempty"`
	ObtainableTime *Object `json:"obtainableTime,omitempty"`
	Crew *Object `json:"crew,omitempty"`
	CommandCost *Object `json:"commandCost,omitempty"`
	CrewContributionTableId *Object `json:"crewContributionTableId,omitempty"`
	UnitClass *Object `json:"unitClass,omitempty"`
	BattlePortraitPrefab *Object `json:"battlePortraitPrefab,omitempty"`
	BattlePortraitNameKey *Object `json:"battlePortraitNameKey,omitempty"`
	ModRecommendation *Object `json:"modRecommendation,omitempty"`
	EffectIconPriorityOverride *Object `json:"effectIconPriorityOverride,omitempty"`
	SummonStatTable *Object `json:"summonStatTable,omitempty"`
	RelicDefinition *RelicDefinition `json:"relicDefinition,omitempty"`
	CapitalUnlockKey *Object `json:"capitalUnlockKey,omitempty"`
	Legend *Object `json:"legend,omitempty"`
	SquadPositionPriority *Object `json:"squadPositionPriority,omitempty"`
	ExampleSquad *Object `json:"exampleSquad,omitempty"`
	Big *Object `json:"big,omitempty"`
	HideInTurnOrder *Object `json:"hideInTurnOrder,omitempty"`
	ThumbImageTurnOrder *Object `json:"thumbImageTurnOrder,omitempty"`
	RequireUltimateUnlock *Object `json:"requireUltimateUnlock,omitempty"`
	BattlePortraitTexture *Object `json:"battlePortraitTexture,omitempty"`
	EraThumbnailName *Object `json:"eraThumbnailName,omitempty"`
	GrantStartTime *Object `json:"grantStartTime,omitempty"`
	FeaturedEndTime *Object `json:"featuredEndTime,omitempty"`
	AssociatedEventId *Object `json:"associatedEventId,omitempty"`
	LoanedUnit *Object `json:"loanedUnit,omitempty"`
}
