/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DynamicDescription struct {
	DescriptionType *Object `json:"descriptionType,omitempty"`
	UnitTexture *Object `json:"unitTexture,omitempty"`
	UnitNameKey *Object `json:"unitNameKey,omitempty"`
	AbilityNameKey *Object `json:"abilityNameKey,omitempty"`
	AbilityDescriptionKey *Object `json:"abilityDescriptionKey,omitempty"`
	AbilityTexture *Object `json:"abilityTexture,omitempty"`
	HeaderKey *Object `json:"headerKey,omitempty"`
	TextKey *Object `json:"textKey,omitempty"`
	MarginLeft *Object `json:"marginLeft,omitempty"`
	TextColumn *Object `json:"textColumn,omitempty"`
	TextAlignment *Object `json:"textAlignment,omitempty"`
	BackgroundOverrideSprite *Object `json:"backgroundOverrideSprite,omitempty"`
}
