/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AbilityModifierData struct {
	BattleSide *Object `json:"battleSide,omitempty"`
	Tint *Object `json:"tint,omitempty"`
	TierKey *Object `json:"tierKey,omitempty"`
	Icon *Object `json:"icon,omitempty"`
}
