/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarSquad struct {
	PlayerId *Object `json:"playerId,omitempty"`
	PlayerName *Object `json:"playerName,omitempty"`
	Power *Object `json:"power,omitempty"`
	Squad *Squad `json:"squad,omitempty"`
	SquadId *Object `json:"squadId,omitempty"`
	SquadStatus *Object `json:"squadStatus,omitempty"`
	LockName *Object `json:"lockName,omitempty"`
	SuccessfulDefends *Object `json:"successfulDefends,omitempty"`
	CrewInfo *Object `json:"crewInfo,omitempty"`
}
