/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Guild struct {
	Profile *GuildProfile `json:"profile,omitempty"`
	Member *Object `json:"member,omitempty"`
	InviteStatus *Object `json:"inviteStatus,omitempty"`
	RaidStatus *Object `json:"raidStatus,omitempty"`
	Inventory *GuildInventory `json:"inventory,omitempty"`
	RaidResult *Object `json:"raidResult,omitempty"`
	Progress *GuildProgress `json:"progress,omitempty"`
	TerritoryBattleStatus *Object `json:"territoryBattleStatus,omitempty"`
	GuildEvents *Object `json:"guildEvents,omitempty"`
	TerritoryBattleResult *Object `json:"territoryBattleResult,omitempty"`
	TerritoryWarStatus *Object `json:"territoryWarStatus,omitempty"`
	RoomAvailable *Object `json:"roomAvailable,omitempty"`
	NextChallengesRefresh *Object `json:"nextChallengesRefresh,omitempty"`
	Stat *Object `json:"stat,omitempty"`
	RecentRaidResult *Object `json:"recentRaidResult,omitempty"`
	RecentTerritoryWarResult *Object `json:"recentTerritoryWarResult,omitempty"`
	LastRaidPointsSummary *Object `json:"lastRaidPointsSummary,omitempty"`
}
