/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AbilityDecisionNode struct {
	DecisionType *Object `json:"decisionType,omitempty"`
	DecisionTarget *Object `json:"decisionTarget,omitempty"`
	Param *Object `json:"param,omitempty"`
	ParamModifier *Object `json:"paramModifier,omitempty"`
	TargetExcludeSelf *Object `json:"targetExcludeSelf,omitempty"`
	Chance *Object `json:"chance,omitempty"`
	Negate *Object `json:"negate,omitempty"`
	DecisionResult *AbilityDecisionResult `json:"decisionResult,omitempty"`
}
