/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AbilityTier struct {
	DescKey *Object `json:"descKey,omitempty"`
	UpgradeDescKey *Object `json:"upgradeDescKey,omitempty"`
	CooldownMaxOverride *Object `json:"cooldownMaxOverride,omitempty"`
	EffectReference *Object `json:"effectReference,omitempty"`
	InteractsWithTag *Object `json:"interactsWithTag,omitempty"`
	BlockingEffectId *Object `json:"blockingEffectId,omitempty"`
	BlockedLocKey *Object `json:"blockedLocKey,omitempty"`
}
