/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EraDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	Icon *Object `json:"icon,omitempty"`
	Episode *Object `json:"episode,omitempty"`
	EraShardCount *Object `json:"eraShardCount,omitempty"`
	Coliseum *ColiseumDefinition `json:"coliseum,omitempty"`
	EraUnitId *Object `json:"eraUnitId,omitempty"`
	ExpectedEraUnitCount *Object `json:"expectedEraUnitCount,omitempty"`
	StartTimeMs *Object `json:"startTimeMs,omitempty"`
	EndTimeMs *Object `json:"endTimeMs,omitempty"`
	EraLevel *Object `json:"eraLevel,omitempty"`
	TotalEraLevelsRewardPreview *Object `json:"totalEraLevelsRewardPreview,omitempty"`
	EraStartJourneyUnitTexture *Object `json:"eraStartJourneyUnitTexture,omitempty"`
	EraStartMarqueeTexture *Object `json:"eraStartMarqueeTexture,omitempty"`
	JourneyUnit *Object `json:"journeyUnit,omitempty"`
	EraStartMarqueeTextureBackground *Object `json:"eraStartMarqueeTextureBackground,omitempty"`
	EraFrameTable *Object `json:"eraFrameTable,omitempty"`
	EraSummaryTexture *Object `json:"eraSummaryTexture,omitempty"`
	EraSummaryTextureBackground *Object `json:"eraSummaryTextureBackground,omitempty"`
	LoanedUnit *Object `json:"loanedUnit,omitempty"`
	StartingLoanedUnitEraLevel *Object `json:"startingLoanedUnitEraLevel,omitempty"`
	MaxLoanedUnitEraLevel *Object `json:"maxLoanedUnitEraLevel,omitempty"`
	MissingJourneyUnit *Object `json:"missingJourneyUnit,omitempty"`
}
