/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoomData struct {
	RoomId *Object `json:"roomId,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	Name *Object `json:"name,omitempty"`
	Topic *Object `json:"topic,omitempty"`
	CreationTime *Object `json:"creationTime,omitempty"`
	OwnerId *Object `json:"ownerId,omitempty"`
}
