/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Category struct {
	Id *Object `json:"id,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	Visible *Object `json:"visible,omitempty"`
	UiFilter *Object `json:"uiFilter,omitempty"`
}
