/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QuestBlockDefinition struct {
	Id *Object `json:"id,omitempty"`
	Title *Object `json:"title,omitempty"`
	QuestPreview *Object `json:"questPreview,omitempty"`
	HeadlineReward *BucketItem `json:"headlineReward,omitempty"`
	HeadlineQuestCompleteRequirement *Object `json:"headlineQuestCompleteRequirement,omitempty"`
}
