/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UnitTierSummary struct {
	BaseId *Object `json:"baseId,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	UnitRelicTier *Object `json:"unitRelicTier,omitempty"`
}
