/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConquestMission struct {
	Id *Object `json:"id,omitempty"`
	BattleDetails *BattleDetails `json:"battleDetails,omitempty"`
	EntryCostRequirement *Object `json:"entryCostRequirement,omitempty"`
	RewardPreview *Object `json:"rewardPreview,omitempty"`
	ConditionalRewardsPreview *Object `json:"conditionalRewardsPreview,omitempty"`
	InstanceFirstCompleteRewardPreview *Object `json:"instanceFirstCompleteRewardPreview,omitempty"`
	RecommendationKey *Object `json:"recommendationKey,omitempty"`
}
