/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BattleDetails struct {
	Id *Object `json:"id,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	BattleEncounter *Object `json:"battleEncounter,omitempty"`
	BattleDurationLimit *Object `json:"battleDurationLimit,omitempty"`
	GrantedAbility *Object `json:"grantedAbility,omitempty"`
	AutoBattleEnabled *Object `json:"autoBattleEnabled,omitempty"`
	BattleSpeedAdjustable *Object `json:"battleSpeedAdjustable,omitempty"`
	RetreatEnabled *Object `json:"retreatEnabled,omitempty"`
	AudioKey *Object `json:"audioKey,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	PveDatacronAllowed *Object `json:"pveDatacronAllowed,omitempty"`
}
