/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EffectTarget struct {
	UnitSelect *Object `json:"unitSelect,omitempty"`
	BattleSide *Object `json:"battleSide,omitempty"`
	UnitClass *Object `json:"unitClass,omitempty"`
	ForceAlignment *Object `json:"forceAlignment,omitempty"`
	Category *EffectTargetCategoryCriteria `json:"category,omitempty"`
	HealthState *Object `json:"healthState,omitempty"`
	StatValue *Object `json:"statValue,omitempty"`
	ActiveEffectTagCriteria *Object `json:"activeEffectTagCriteria,omitempty"`
	BattleDeploymentState *Object `json:"battleDeploymentState,omitempty"`
	Id *Object `json:"id,omitempty"`
	ExcludeSelf *Object `json:"excludeSelf,omitempty"`
	ExcludeSelectedTarget *Object `json:"excludeSelectedTarget,omitempty"`
	RequiredCategory *EffectTargetCategoryCriteria `json:"requiredCategory,omitempty"`
	RequiredActiveEffectTagCriteria *Object `json:"requiredActiveEffectTagCriteria,omitempty"`
}
