/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryCovertZoneDefinition struct {
	ZoneDefinition *TerritoryZoneDefinition `json:"zoneDefinition,omitempty"`
	CampaignElementIdentifier *CampaignElementIdentifier `json:"campaignElementIdentifier,omitempty"`
	VictoryReward *Object `json:"victoryReward,omitempty"`
	DisableRewardOnMap *Object `json:"disableRewardOnMap,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
}
