/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarDefinition struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	PrefabName *Object `json:"prefabName,omitempty"`
	RoundCount *Object `json:"roundCount,omitempty"`
	IconPrefab *Object `json:"iconPrefab,omitempty"`
	DetailImage *Object `json:"detailImage,omitempty"`
	RoundTallyDuration *Object `json:"roundTallyDuration,omitempty"`
	DynamicDescription *Object `json:"dynamicDescription,omitempty"`
	FirstRewardPreview *Object `json:"firstRewardPreview,omitempty"`
	SecondRewardPreview *Object `json:"secondRewardPreview,omitempty"`
	MatchmakingDuration *Object `json:"matchmakingDuration,omitempty"`
	SetupDuration *Object `json:"setupDuration,omitempty"`
	GrantedAbilities *Object `json:"grantedAbilities,omitempty"`
	JoinEventActionCapKey *Object `json:"joinEventActionCapKey,omitempty"`
	MinParticipants *Object `json:"minParticipants,omitempty"`
	TerrainPrefabName *Object `json:"terrainPrefabName,omitempty"`
	MaxParticipants *Object `json:"maxParticipants,omitempty"`
	MinScoreRequirement *Object `json:"minScoreRequirement,omitempty"`
	WarConflictZoneDefinition *Object `json:"warConflictZoneDefinition,omitempty"`
	ReconZoneDefinition *Object `json:"reconZoneDefinition,omitempty"`
	StatCategory *Object `json:"statCategory,omitempty"`
	RewardStructure *Object `json:"rewardStructure,omitempty"`
	UniqueJoinId *Object `json:"uniqueJoinId,omitempty"`
	HideLeaderboard *Object `json:"hideLeaderboard,omitempty"`
	LocalNotifications *Object `json:"localNotifications,omitempty"`
	MinMemberLevelForReportingOpponent *Object `json:"minMemberLevelForReportingOpponent,omitempty"`
	MinMemberLevelForCommandingGuild *Object `json:"minMemberLevelForCommandingGuild,omitempty"`
	CommandNotificationCooldownDuration *Object `json:"commandNotificationCooldownDuration,omitempty"`
	MapTypeNameKey *Object `json:"mapTypeNameKey,omitempty"`
	ShowTimerOnEvent *Object `json:"showTimerOnEvent,omitempty"`
	RestrictSetupDuringAttackPhase *Object `json:"restrictSetupDuringAttackPhase,omitempty"`
	DefaultCharacterBattleEnvironments *Object `json:"defaultCharacterBattleEnvironments,omitempty"`
	DefaultShipBattleEnvironments *Object `json:"defaultShipBattleEnvironments,omitempty"`
	MinimapPrefab *Object `json:"minimapPrefab,omitempty"`
	DefensiveCharacterDeployWarningThreshold *Object `json:"defensiveCharacterDeployWarningThreshold,omitempty"`
	DefensiveShipDeployWarningThreshold *Object `json:"defensiveShipDeployWarningThreshold,omitempty"`
	LeaderboardKey *Object `json:"leaderboardKey,omitempty"`
	MinPlayerScoreRequirement *Object `json:"minPlayerScoreRequirement,omitempty"`
}
