/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarStatus struct {
	InstanceId *Object `json:"instanceId,omitempty"`
	DefinitionId *Object `json:"definitionId,omitempty"`
	CurrentRound *Object `json:"currentRound,omitempty"`
	CurrentRoundEndTime *Object `json:"currentRoundEndTime,omitempty"`
	ChannelId *Object `json:"channelId,omitempty"`
	HomeGuild *TerritoryWarGuildStatus `json:"homeGuild,omitempty"`
	AwayGuild *TerritoryWarGuildStatus `json:"awayGuild,omitempty"`
	PlayerStatus *TerritoryWarPlayerStatus `json:"playerStatus,omitempty"`
	CurrentStat *Object `json:"currentStat,omitempty"`
	OptedInMemberId *Object `json:"optedInMemberId,omitempty"`
	OptedInMember *Object `json:"optedInMember,omitempty"`
	ExcludedFromWar *Object `json:"excludedFromWar,omitempty"`
	HasReportedEnemyGuild *Object `json:"hasReportedEnemyGuild,omitempty"`
	LastCommandNotificationTime *Object `json:"lastCommandNotificationTime,omitempty"`
	MapCompletedEarly *Object `json:"mapCompletedEarly,omitempty"`
}
