/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConquestDifficulty struct {
	MinGp *Object `json:"minGp,omitempty"`
	Sector *Object `json:"sector,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	Id *Object `json:"id,omitempty"`
	RankRewardPreview *Object `json:"rankRewardPreview,omitempty"`
	ImmediateRankRewardPreview *Object `json:"immediateRankRewardPreview,omitempty"`
	RecommendedMinGp *Object `json:"recommendedMinGp,omitempty"`
	PremiumImmediateRankRewardPreview *Object `json:"premiumImmediateRankRewardPreview,omitempty"`
}
