/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContextualMessageGroup struct {
	GroupId *Object `json:"groupId,omitempty"`
	StartMessage *Object `json:"startMessage,omitempty"`
	Message *Object `json:"message,omitempty"`
	Priority *Object `json:"priority,omitempty"`
	CanDismissWhileHidden *Object `json:"canDismissWhileHidden,omitempty"`
	StartTime *Object `json:"startTime,omitempty"`
	EndTime *Object `json:"endTime,omitempty"`
	IsFtue *Object `json:"isFtue,omitempty"`
}
