/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Requirement struct {
	EvalType *Object `json:"evalType,omitempty"`
	RequirementItem *Object `json:"requirementItem,omitempty"`
	Id *Object `json:"id,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
}
