/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LeaderboardPlayer struct {
	Id *Object `json:"id,omitempty"`
	Name *Object `json:"name,omitempty"`
	Level *Object `json:"level,omitempty"`
	Guild *LeaderboardGuild `json:"guild,omitempty"`
	IsFake *Object `json:"isFake,omitempty"`
	PvpStatus *LeaderboardStatus `json:"pvpStatus,omitempty"`
	SquadUnit *Object `json:"squadUnit,omitempty"`
	Title *Object `json:"title,omitempty"`
	Power *Object `json:"power,omitempty"`
	Portrait *Object `json:"portrait,omitempty"`
	SeasonsLifetimeScore *Object `json:"seasonsLifetimeScore,omitempty"`
	SeasonLeagueId *Object `json:"seasonLeagueId,omitempty"`
	PlayerRating *PlayerRating `json:"playerRating,omitempty"`
	Tier *Object `json:"tier,omitempty"`
}
