/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryBattleStatus struct {
	InstanceId *Object `json:"instanceId,omitempty"`
	DefinitionId *Object `json:"definitionId,omitempty"`
	ConflictZoneStatus *Object `json:"conflictZoneStatus,omitempty"`
	StrikeZoneStatus *Object `json:"strikeZoneStatus,omitempty"`
	ReconZoneStatus *Object `json:"reconZoneStatus,omitempty"`
	PlayerStatus *TerritoryBattlePlayerStatus `json:"playerStatus,omitempty"`
	CurrentRound *Object `json:"currentRound,omitempty"`
	CurrentRoundEndTime *Object `json:"currentRoundEndTime,omitempty"`
	ChannelId *Object `json:"channelId,omitempty"`
	CovertZoneStatus *Object `json:"covertZoneStatus,omitempty"`
	CurrentStat *Object `json:"currentStat,omitempty"`
	LastCommandNotificationTime *Object `json:"lastCommandNotificationTime,omitempty"`
	MapCompletedEarly *Object `json:"mapCompletedEarly,omitempty"`
	Selected *Object `json:"selected,omitempty"`
}
