/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventBonus struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	IconKey *Object `json:"iconKey,omitempty"`
	ScoreModifier *Object `json:"scoreModifier,omitempty"`
}
