/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AbilityReference struct {
	AbilityId *Object `json:"abilityId,omitempty"`
	RequiredTier *Object `json:"requiredTier,omitempty"`
	RequiredRarity *Object `json:"requiredRarity,omitempty"`
	RequiredSkillTier *Object `json:"requiredSkillTier,omitempty"`
	RequiredRelicTier *Object `json:"requiredRelicTier,omitempty"`
	OverrideAlwaysDisplayInBattleUi *Object `json:"overrideAlwaysDisplayInBattleUi,omitempty"`
	OverrideIcon *Object `json:"overrideIcon,omitempty"`
	OverrideNameKey *Object `json:"overrideNameKey,omitempty"`
	OverrideDescKey *Object `json:"overrideDescKey,omitempty"`
	PowerAdditiveTag *Object `json:"powerAdditiveTag,omitempty"`
	UnlockRecipeId *Object `json:"unlockRecipeId,omitempty"`
	InheritMappingId *Object `json:"inheritMappingId,omitempty"`
}
