/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Environment struct {
	Prefab *Object `json:"prefab,omitempty"`
	Layout *Object `json:"layout,omitempty"`
	LayoutPrefab *Object `json:"layoutPrefab,omitempty"`
}
