/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SystemModifier struct {
	Id *Object `json:"id,omitempty"`
	ScaleItemModifier *ScaleItemModifier `json:"scaleItemModifier,omitempty"`
	Location *Object `json:"location,omitempty"`
	AdditionalItemModifier *AdditionalItemModifier `json:"additionalItemModifier,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	ActionLink *ActionLink `json:"actionLink,omitempty"`
}
