/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CharacterQuestLine struct {
	StartTime *Object `json:"startTime,omitempty"`
	EndTime *Object `json:"endTime,omitempty"`
	CharacterQuestBlock *Object `json:"characterQuestBlock,omitempty"`
	UnitId *Object `json:"unitId,omitempty"`
	Image *Object `json:"image,omitempty"`
	TitleKey *Object `json:"titleKey,omitempty"`
}
