/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2Xx8 struct {
	Name *Object `json:"name,omitempty"`
	Level *Object `json:"level,omitempty"`
	AllyCode *Object `json:"allyCode,omitempty"`
	PlayerId *Object `json:"playerId,omitempty"`
	RosterUnit *Object `json:"rosterUnit,omitempty"`
	ProfileStat *Object `json:"profileStat,omitempty"`
	GuildId *Object `json:"guildId,omitempty"`
	GuildName *Object `json:"guildName,omitempty"`
	GuildLogoBackground *Object `json:"guildLogoBackground,omitempty"`
	GuildBannerColor *Object `json:"guildBannerColor,omitempty"`
	GuildBannerLogo *Object `json:"guildBannerLogo,omitempty"`
	PvpProfile *Object `json:"pvpProfile,omitempty"`
	SelectedPlayerTitle *PlayerTitle `json:"selectedPlayerTitle,omitempty"`
	UnlockedPlayerTitle *Object `json:"unlockedPlayerTitle,omitempty"`
	GuildTypeId *Object `json:"guildTypeId,omitempty"`
	LocalTimeZoneOffsetMinutes *Object `json:"localTimeZoneOffsetMinutes,omitempty"`
	LastActivityTime *Object `json:"lastActivityTime,omitempty"`
	SelectedPlayerPortrait *PlayerPortrait `json:"selectedPlayerPortrait,omitempty"`
	UnlockedPlayerPortrait *Object `json:"unlockedPlayerPortrait,omitempty"`
	SeasonStatus *Object `json:"seasonStatus,omitempty"`
	LifetimeSeasonScore *Object `json:"lifetimeSeasonScore,omitempty"`
	PlayerRating *PlayerRating `json:"playerRating,omitempty"`
	Datacron *Object `json:"datacron,omitempty"`
	NucleusId *Object `json:"nucleusId,omitempty"`
	EraUnitStatus *Object `json:"eraUnitStatus,omitempty"`
}
