/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Stat struct {
	UnitStatId *Object `json:"unitStatId,omitempty"`
	StatValueDecimal *Object `json:"statValueDecimal,omitempty"`
	UnscaledDecimalValue *Object `json:"unscaledDecimalValue,omitempty"`
	UiDisplayOverrideValue *Object `json:"uiDisplayOverrideValue,omitempty"`
	Scalar *Object `json:"scalar,omitempty"`
}
