/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BattleUnitState struct {
	UnitId *Object `json:"unitId,omitempty"`
	HealthPercent *Object `json:"healthPercent,omitempty"`
	AbilityState *Object `json:"abilityState,omitempty"`
	ProgressItem *Object `json:"progressItem,omitempty"`
	CurrentHealth *Object `json:"currentHealth,omitempty"`
	ShieldPercent *Object `json:"shieldPercent,omitempty"`
	TurnPercent *Object `json:"turnPercent,omitempty"`
	MaxHealth *Object `json:"maxHealth,omitempty"`
	HasFled *Object `json:"hasFled,omitempty"`
	MaxShield *Object `json:"maxShield,omitempty"`
	IsCommander *Object `json:"isCommander,omitempty"`
	IsDeployed *Object `json:"isDeployed,omitempty"`
	CurrentShield *Object `json:"currentShield,omitempty"`
	OverkillItem *Object `json:"overkillItem,omitempty"`
	OverkillDamage *Object `json:"overkillDamage,omitempty"`
	BattleContextMaxShield *Object `json:"battleContextMaxShield,omitempty"`
	IsUnscathed *Object `json:"isUnscathed,omitempty"`
}
