/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConquestSector struct {
	Id *Object `json:"id,omitempty"`
	Node *Object `json:"node,omitempty"`
	PrefabName *Object `json:"prefabName,omitempty"`
	ArtTile *Object `json:"artTile,omitempty"`
	TitleKey *Object `json:"titleKey,omitempty"`
	EnvironmentTitleKey *Object `json:"environmentTitleKey,omitempty"`
	BackgroundPrefabName *Object `json:"backgroundPrefabName,omitempty"`
}
