/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EnergyRewardInstance struct {
	Type_ *Object `json:"type,omitempty"`
	Start *Object `json:"start,omitempty"`
	Duration *Object `json:"duration,omitempty"`
	Amount *Object `json:"amount,omitempty"`
}
