/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CampaignMissionEnemyPreview struct {
	BaseEnemyItem *BucketItem `json:"baseEnemyItem,omitempty"`
	EnemyLevel *Object `json:"enemyLevel,omitempty"`
	EnemyTier *Object `json:"enemyTier,omitempty"`
	ThreatLevel *Object `json:"threatLevel,omitempty"`
	ThumbnailName *Object `json:"thumbnailName,omitempty"`
	PrefabName *Object `json:"prefabName,omitempty"`
	DisplayedEnemy *Object `json:"displayedEnemy,omitempty"`
	UnitClass *Object `json:"unitClass,omitempty"`
	EnemyForceAlignment *Object `json:"enemyForceAlignment,omitempty"`
	EnemyRelicTier *Object `json:"enemyRelicTier,omitempty"`
	ZetaCount *Object `json:"zetaCount,omitempty"`
	IsGalacticLegend *Object `json:"isGalacticLegend,omitempty"`
	IsUltimateUnlocked *Object `json:"isUltimateUnlocked,omitempty"`
	OmicronCount *Object `json:"omicronCount,omitempty"`
	EraLevel *Object `json:"eraLevel,omitempty"`
	EraThumbnailName *Object `json:"eraThumbnailName,omitempty"`
}
