/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GuildRaid struct {
	Id *Object `json:"id,omitempty"`
	Priority *Object `json:"priority,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	SummaryKey *Object `json:"summaryKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	Image *Object `json:"image,omitempty"`
	SquadType *Object `json:"squadType,omitempty"`
	CampaignElementIdentifier *CampaignElementIdentifier `json:"campaignElementIdentifier,omitempty"`
	IconPrefab *Object `json:"iconPrefab,omitempty"`
	PromotionKey *Object `json:"promotionKey,omitempty"`
	PortraitIcon *Object `json:"portraitIcon,omitempty"`
	RaidSim *GuildRaidSim `json:"raidSim,omitempty"`
	InfoImage *Object `json:"infoImage,omitempty"`
	Lockout *GuildRaidLockout `json:"lockout,omitempty"`
	LegacyRaid *Object `json:"legacyRaid,omitempty"`
	CurrencyReward *Object `json:"currencyReward,omitempty"`
	GuildRewardsRequireAttempt *Object `json:"guildRewardsRequireAttempt,omitempty"`
	AudioVictoryKey *Object `json:"audioVictoryKey,omitempty"`
	AudioDefeatKey *Object `json:"audioDefeatKey,omitempty"`
}
