/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2Xx6 struct {
	Config *Object `json:"config,omitempty"`
	AssetVersion *Object `json:"assetVersion,omitempty"`
	AssetSubpath *Object `json:"assetSubpath,omitempty"`
	TexFormat *Object `json:"texFormat,omitempty"`
	ServerTimestamp *Object `json:"serverTimestamp,omitempty"`
	DebugMode *Object `json:"debugMode,omitempty"`
	LatestLocalizationBundleVersion *Object `json:"latestLocalizationBundleVersion,omitempty"`
	LatestGamedataVersion *Object `json:"latestGamedataVersion,omitempty"`
	ResourceCacheMemoryLimit *Object `json:"resourceCacheMemoryLimit,omitempty"`
	GamedataRevision *Object `json:"gamedataRevision,omitempty"`
	MonoExtraMemoryAllocationDivisor *Object `json:"monoExtraMemoryAllocationDivisor,omitempty"`
	QualityData *ClientQualityData `json:"qualityData,omitempty"`
	LatestLocalizationRevision *Object `json:"latestLocalizationRevision,omitempty"`
	ServerVersion *Object `json:"serverVersion,omitempty"`
	ClientCache *Object `json:"clientCache,omitempty"`
	EadpParameters *EadpParameters `json:"eadpParameters,omitempty"`
	LatestSegmentedContentVersion *Object `json:"latestSegmentedContentVersion,omitempty"`
}
