/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryBattleConflictZoneDefinition struct {
	CombatType *Object `json:"combatType,omitempty"`
	VictoryPointRewards *Object `json:"victoryPointRewards,omitempty"`
	ZoneDefinition *TerritoryZoneDefinition `json:"zoneDefinition,omitempty"`
	ConflictImage *Object `json:"conflictImage,omitempty"`
	TerritoryBattleZoneUnitType *Object `json:"territoryBattleZoneUnitType,omitempty"`
	AlternateChaseIcon *Object `json:"alternateChaseIcon,omitempty"`
	ForceAlignment *Object `json:"forceAlignment,omitempty"`
	IsBonus *Object `json:"isBonus,omitempty"`
	IsNewestBonusZone *Object `json:"isNewestBonusZone,omitempty"`
	FlipChaseIconX *Object `json:"flipChaseIconX,omitempty"`
	FlipChaseIconY *Object `json:"flipChaseIconY,omitempty"`
}
