/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CraftingMaterialDef struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescKey *Object `json:"descKey,omitempty"`
	IconKey *Object `json:"iconKey,omitempty"`
	SellValue *CurrencyItem `json:"sellValue,omitempty"`
	LookupMission *Object `json:"lookupMission,omitempty"`
	XpValue *Object `json:"xpValue,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	Rarity *Object `json:"rarity,omitempty"`
	TrainingCost *Object `json:"trainingCost,omitempty"`
	TrainingCostMaxLevel *Object `json:"trainingCostMaxLevel,omitempty"`
	UnitDefReference *Object `json:"unitDefReference,omitempty"`
	Tier *Object `json:"tier,omitempty"`
	ObtainableTime *Object `json:"obtainableTime,omitempty"`
	RaidLookup *Object `json:"raidLookup,omitempty"`
	ActionLinkLookup *Object `json:"actionLinkLookup,omitempty"`
	RecipeId *Object `json:"recipeId,omitempty"`
	RaidImmediateLookup *Object `json:"raidImmediateLookup,omitempty"`
}
