/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DatacronAffix struct {
	TargetRule *Object `json:"targetRule,omitempty"`
	AbilityId *Object `json:"abilityId,omitempty"`
	StatType *Object `json:"statType,omitempty"`
	StatValue *Object `json:"statValue,omitempty"`
	Tag *Object `json:"tag,omitempty"`
	RequiredUnitTier *Object `json:"requiredUnitTier,omitempty"`
	RequiredRelicTier *Object `json:"requiredRelicTier,omitempty"`
	ScopeIcon *Object `json:"scopeIcon,omitempty"`
}
