/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryReconZoneDefinition struct {
	ZoneDefinition *TerritoryZoneDefinition `json:"zoneDefinition,omitempty"`
	PlatoonDefinition *Object `json:"platoonDefinition,omitempty"`
	AbilityImage *Object `json:"abilityImage,omitempty"`
	AbilityShortDescKey *Object `json:"abilityShortDescKey,omitempty"`
	AbilityLongDescKey *Object `json:"abilityLongDescKey,omitempty"`
	GoalDescKey *Object `json:"goalDescKey,omitempty"`
	GoalImage *Object `json:"goalImage,omitempty"`
	UnitRarity *Object `json:"unitRarity,omitempty"`
	RewardDescKey *Object `json:"rewardDescKey,omitempty"`
	SubTitleKey *Object `json:"subTitleKey,omitempty"`
	GrantedAbilities *Object `json:"grantedAbilities,omitempty"`
	StrategicAbilities *Object `json:"strategicAbilities,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	TerritoryBattleZoneUnitType *Object `json:"territoryBattleZoneUnitType,omitempty"`
	UnitRelicTier *Object `json:"unitRelicTier,omitempty"`
}
