/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GuildInviteStatus struct {
	GuildId *Object `json:"guildId,omitempty"`
	ExpireTime *Object `json:"expireTime,omitempty"`
	PlayerId *Object `json:"playerId,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	LeaderUnit *Unit `json:"leaderUnit,omitempty"`
	SentTime *Object `json:"sentTime,omitempty"`
	PlayerLevel *Object `json:"playerLevel,omitempty"`
	PlayerName *Object `json:"playerName,omitempty"`
}
