/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LightspeedTokenDefinition struct {
	Id *Object `json:"id,omitempty"`
	UnitUpgrade *UnitUpgrade `json:"unitUpgrade,omitempty"`
	IncludeTag *Object `json:"includeTag,omitempty"`
	ExcludeTag *Object `json:"excludeTag,omitempty"`
	ReleaseEraTag *Object `json:"releaseEraTag,omitempty"`
	DismantlingReward *Object `json:"dismantlingReward,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	TokenTierLargeSprite *Object `json:"tokenTierLargeSprite,omitempty"`
	TokenTierSmallSprite *Object `json:"tokenTierSmallSprite,omitempty"`
	TokenImage *Object `json:"tokenImage,omitempty"`
	CombatType *Object `json:"combatType,omitempty"`
	ApplicableUnitDefs *Object `json:"applicableUnitDefs,omitempty"`
	LookupMission *Object `json:"lookupMission,omitempty"`
	RaidLookup *Object `json:"raidLookup,omitempty"`
	ActionLinkLookup *Object `json:"actionLinkLookup,omitempty"`
	RaidImmediateLookup *Object `json:"raidImmediateLookup,omitempty"`
}
