/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryWarParticipant struct {
	MemberId *Object `json:"memberId,omitempty"`
	JoinTime *Object `json:"joinTime,omitempty"`
	Eligible *Object `json:"eligible,omitempty"`
	Power *Object `json:"power,omitempty"`
}
