/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConquestNode struct {
	Id *Object `json:"id,omitempty"`
	Type_ *Object `json:"type,omitempty"`
	ConquestMissionId *Object `json:"conquestMissionId,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	EnemyUnitPreview *Object `json:"enemyUnitPreview,omitempty"`
	ConquestCompletionNode *Object `json:"conquestCompletionNode,omitempty"`
	UnlockRequirementId *Object `json:"unlockRequirementId,omitempty"`
	Style *Object `json:"style,omitempty"`
	FinishSector *Object `json:"finishSector,omitempty"`
}
