/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TerritoryTournamentDuelZoneDefinition struct {
	ZoneDefinition *TerritoryZoneDefinition `json:"zoneDefinition,omitempty"`
	DuelImage *Object `json:"duelImage,omitempty"`
	DuelRequirement *Object `json:"duelRequirement,omitempty"`
	DuelDetail *Object `json:"duelDetail,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	DefenseEntryCategoryAllowed *EntryCategoryAllowed `json:"defenseEntryCategoryAllowed,omitempty"`
	BattleEnvironments *Object `json:"battleEnvironments,omitempty"`
	PointStructure *TerritoryWarPointStructure `json:"pointStructure,omitempty"`
	SaveSquadZoneNumber *Object `json:"saveSquadZoneNumber,omitempty"`
}
