/*
 * swgoh-comlink
 *
 * An API for sending requests to Star Wars Galaxy of Heroes' game services
 *
 * API version: 0.38.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Campaign struct {
	Id *Object `json:"id,omitempty"`
	NameKey *Object `json:"nameKey,omitempty"`
	DescriptionKey *Object `json:"descriptionKey,omitempty"`
	Image *Object `json:"image,omitempty"`
	CampaignType *Object `json:"campaignType,omitempty"`
	CampaignMap *Object `json:"campaignMap,omitempty"`
	Progress *Object `json:"progress,omitempty"`
	UnlockRequirementLocalizationKey *Object `json:"unlockRequirementLocalizationKey,omitempty"`
	DailyBattleCapKey *Object `json:"dailyBattleCapKey,omitempty"`
	EntryCategoryAllowed *EntryCategoryAllowed `json:"entryCategoryAllowed,omitempty"`
	GrindEnabled *Object `json:"grindEnabled,omitempty"`
}
